<?
$title = 'Page Not FoundPage Not Found (404)';
$description = 'Page Not Found (404)';
$keywords = '';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1>
            <b>404</b> - PAGE NOT FOUND
        </h1>
    </div>

    <div class="bg-silver">
        <div class="container p-5 solucoes">

            <div class=" mx-5 px-5">

                <p>It looks like you're lost...</p>
                <p>The page you are trying to access does not exist or has been moved.</p>
                <p>Don't worry, here are some options to continue browsing:</p>
                <ul>
                    <li><a href="./">Return to the Homepage</a></li>
                    <li><a href="contato/">Contact Us</a></li>
                </ul>
                <p>If you believe this is an error, please contact our technical support.</p>
            </div>
        </div>
    </div>


</main>

<? include '_footer.phtml'; ?>