<!-- FOOTER -->

<footer class="pt-4 pb-0">

    <div class="text-center brand">
        <a href="./">
            <img src="images/controlar-logo-black.png" alt="">
        </a>
    </div>

    <div class="only-mobile container text-white text-center">

        <h3 class="">Through technology, we strive to provide our clients with innovative solutions to reduce environmental impact and promote sustainability.</h4>

            <a href="#" class="btn btn-whatsapp my-4">
                <img src="images/ico-whatsapp.png" alt=""> TALK TO A SPECIALIST
            </a>

            <a href="#" target="_blank" class="btn btn-youtube my-4">
                <img src="images/ico-youtube-white.png" alt="">
            </a><br>
    </div>

    <div class="menu container d-flex justify-content-between">

        <!-- Links principais -->
        <section>
            <ul style=" list-style-type: none; padding: 0;">
                <li><a href="en/dust-suppression/" target="_self">What is Dust Suppression?</a></li>
                <li><a href="en/our-partner-clients/" target="_self">Clients and Partners</a></li>
                <li><a href="en/about-us/" target="_self">About Us</a></li>
                <li><a href="en/contact/" target="_self">Contact</a>
                </li>
            </ul>
        </section>

        <!-- Serviços de aspersão -->
        <section>
            <ul style="list-style-type: none; padding: 0;">
                <li><a href="en/dust-suppression-in-crushing-plants/" target="_self">Dust Suppression In Crushing</a></li>
                <li><a href="en/dust-suppression-in-truck-buckets/" target="_self">Dust Suppression In Truck Buckets</a></li>
                <li><a href="en/dust-suppression-in-ore-yards/" target="_self">Dust Suppression In Ore Yards</a></li>
                <li><a href="en/dust-suppression-in-ore-wagons/" target="_self">Dust Suppression In Ore Wagons</a></li>
                <li><a href="en/dust-suppression-on-haul-roads/" target="_self">Dust Suppression On Haul Roads</a></li>
                <li><a href="en/wheel-and-chassis-washer/" target="_self">Wheel And Chassis Washer</a></li>
                <li><a href="en/equipment-rental-for-dust-suppression-and-wheel-washers/" target="_self">Equipment Rental</a></li>
            </ul>
        </section>

        <section class="social">
            FOLLOW US ON<br> OUR SOCIAL MEDIA<br>
            <a href="https://www.youtube.com/@controlarsistemas3442" target="_blank"><img src="images/ico-youtube.png" class="zoom" alt=""></a>
        </section>


    </div>
    <div class="sign">
        <div class="container">
            <a href="https://agenciadecriacao.com.br" target="_blank">
                <img src="images/agencia-criacao.png" alt="">
            </a>
        </div>
    </div>

    <? include 'cookie.phtml'; ?>

</footer><!-- /.FOOTER -->


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script>
    window.jQuery || document.write('<script src="/assets/js/vendor/jquery-slim.min.js"><\/script>')
</script>
<script src="/dist/js/bootstrap.bundle.min.js?v=2"
    integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o"
    crossorigin="anonymous"></script>

</body>

</html>