<?
$title = 'Contact Us | Solution for Dust Emission Control';
$description = 'Get in touch with Controlar and discover the ideal solution for dust emission control in your industry. Specialized support and personalized service.';
$keywords = 'solution for dust emission control';
include '_header.phtml';
?>

<main role="main" class="internal">


    <div class="breadcrumb container">
        <h1><b>CONTACT US</b></h1>
    </div>

    <div class="relative h-10">
        <div class="bg-white max-height-500"></div>
    </div>

    <div class="container contato px-5 pb-5">

        <div class="box">
            <h1 class="px-3"><strong>We have the best solution for dust emission control!</h1>


            <form action="#" method="POST">

                <h2>REQUEST A COMMERCIAL CONTACT</h2>
                <h3><strong>WITH ONE OF OUR SPECIALISTS!</strong></h3>

                <input type="text" name="nome" placeholder="Full Name *" required>
                <input type="email" name="email" placeholder="Email *" required>
                <input type="text" placeholder="Company Name *" name="empresa" required>
                <input type="tel" placeholder="Phone Number with Area Code *" name="telefone" required>

                <select id="produto" name="produto">
                    <option value="" selected disabled>Which product are you interested in?</option>
                    <option value="produto1">Dust Suppression in Truck Buckets</option>
                    <option value="produto2">Dust Suppression on Haul Roads</option>
                    <option value="produto3">Dust Suppression in Ore Wagons</option>
                    <option value="produto4">Dust Suppression in Ore Yards</option>
                    <option value="produto5">Wheel and Chassis Washer</option>
                    <option value="produto6">Dust Suppression in Crushing Plants</option>
                    <option value="produto7">Equipment Rental</option>
                </select>

                <select id="como_conheceucomo_conheceu" name="como_conheceu">
                    <option value="" selected disabled>How did you learn about Controlar?</option>
                    <option value="r1">Google Search</option>
                    <option value="r2">On Linkedin</option>
                    <option value="r3">On Instagram</option>
                    <option value="r4">On YouTube</option>
                    <option value="r5">At Trade Events</option>
                    <option value="r6">Third-Party Recommendation</option>
                </select>

                <textarea name="texto"
                    placeholder="Please provide details about your project, including the challenges you are facing and your specific needs. Our team will get in touch with you as soon as possible."
                    id=""></textarea>

                <div class="d-flex justify-content-between">
                    <p>* All fields are required</p>
                    <button type="submit">TALK TO A CONSULTANT</button>
                </div>
            </form>
        </div>


    </div><!-- /.contato -->


</main>


<? include '_footer.phtml'; ?>