<?
$title = 'Contact Us | Solution for Dust Emission Control';
$description = 'Get in touch with Controlar and discover the ideal solution for dust emission control in your industry. Specialized support and personalized service.';
$keywords = 'solution for dust emission control';
include '_header.phtml';
?>

<main role="main" class="internal">


    <div class="breadcrumb container">
        <h1><b>CONTACT US</b></h1>
    </div>

    <div class="relative h-10">
        <div class="bg-white max-height-500"></div>
    </div>

    <div class="container contato px-5 pb-5">

        <div class="box">
            <h1 class="px-3"><strong>We have the best solution for dust emission control!</h1>



            <form id="meuFormulario" action="_mailSender.php" method="POST">

                <h2>REQUEST A COMMERCIAL CONTACT</h2>
                <h3><strong>WITH ONE OF OUR SPECIALISTS!</strong></h3>


                <input type="text" name="nome" placeholder="Full Name *" required>
                <input type="email" name="email" placeholder="Email *" required>
                <input type="text" placeholder="Company Name *" name="empresa" required>
                <input type="tel" placeholder="Phone Number with Area Code *" name="telefone" required>

                <select id="produto" name="produto">
                    <option value="" selected disabled>Which product are you interested in?</option>
                    <option value="Dust Suppression in Truck Buckets">Dust Suppression in Truck Buckets</option>
                    <option value="Dust Suppression on Haul Roads">Dust Suppression on Haul Roads</option>
                    <option value="Dust Suppression in Ore Wagons">Dust Suppression in Ore Wagons</option>
                    <option value="Dust Suppression in Ore Yards">Dust Suppression in Ore Yards</option>
                    <option value="Wheel and Chassis Washer">Wheel and Chassis Washer</option>
                    <option value="Dust Suppression in Crushing Plants">Dust Suppression in Crushing Plants</option>
                    <option value="Equipment Rental">Equipment Rental</option>
                </select>

                <select id="como_conheceucomo_conheceu" name="como_conheceu">
                    <option value="" selected disabled>How did you learn about Controlar?</option>
                    <option value="Google Search">Google Search</option>
                    <option value="On Linkedin">On Linkedin</option>
                    <option value="On Instagram">On Instagram</option>
                    <option value="On YouTube">On YouTube</option>
                    <option value="At Trade Events">At Trade Events</option>
                    <option value="Third-Party Recommendation">Third-Party Recommendation</option>
                </select>

                <textarea name="texto"
                    placeholder="Please provide details about your project, including the challenges you are facing and your specific needs. Our team will get in touch with you as soon as possible."
                    id=""></textarea>

                <div id="mensagemFeedback"></div>

                <input type="hidden" name="type" value="orcamento" />
                <input type="hidden" id="recaptchaToken" name="recaptchaToken" value="" />


                <div class="d-flex justify-content-between">
                    <p>* All fields are required</p>
                    <button type="submit" id="meuBotao">TALK TO A CONSULTANT</button>
                </div>
            </form>

        </div>


    </div><!-- /.contato -->


</main>


<? include '_footer.phtml'; ?>