<?
$title = 'Despoeiramento | Soluções Eficientes para Controle de Poeira';
$description = 'Descubra as melhores soluções em despoeiramento com a Controlar. Controle de poeira eficiente e sustentável para diversos setores industriais.';
$keywords = 'despoeiramento';
include '_header.phtml';
?>

<main role="main" class="internal">


    <div class="breadcrumb container">
        <h1><b>DUST SUPPRESSION</b></h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 despoeiramento">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">What is dust?</h2>
                <p><b>Dust</b> consists of small particles of various origins, with different structures and compositions, that settle after being suspended in the air, causing environmental contamination.</p>
            </div>
        </div>
    </div>


    <div class="container p-5 despoeiramento bg-none">
        <div class="mx-5 px-5 mb-5">
            <h2 class="big">What is dust suppression?</h2>

            <p><b>Dust suppression</b> is used to prevent airborne particulate matter from being released directly into the environment. In other words, dust suppression is the process of controlling airborne dust emissions.</p>

            <p><b>Dust suppression systems</b> are effective dust control methods that reduce operational costs while minimizing water and energy consumption.</p>
        </div>

        <div class="p-5 mx-5 bg-white">
            <h2 class="big">Discover our dust suppression system solutions for:</h2>
            <ul class="list">
                <li><a href="en/dust-suppression-on-haul-roads/" target="_self">Haul roads</a></li>
                <li><a href="en/dust-suppression-in-crushing-plants/" target="_self">Crushing unit conveyor belts</a></li>
                <li><a href="en/dust-suppression-in-ore-yards/" target="_self">Ore stockpiles</a></li>
                <li><a href="en/wheel-and-chassis-washer" target="_self">Wheel and chassis washers</a></li>
                <li><a href="en/dust-suppression-in-ore-wagons/" target="_self">Ore wagons</a></li>
            </ul>
        </div>
    </div>



    <div class="despoeiramento bg-green">
        <div class="container p-5">
            <div class="mx-5 px-5">
                <h2 class="big">FIELDS OF APPLICATION:</h2>
                <ul class="list">
                    <li>Civil construction</li>
                    <li>Industry</li>
                    <li>Mining</li>
                    <li>Steel industry</li>
                </ul>
            </div>
        </div>
    </div>




    <div class="p-5 text-center">
        <a href="en/contact/" target="_self" class="btn btn-more fs-2">REQUEST A CONTACT</a>
    </div>

</main>


<? include '_footer.phtml'; ?>