<?
$title = 'Water and Polymer Sprayer for Truck Buckets | Efficient Dust Control';
$description = 'The Water and Polymer Sprayer for Truck Buckets reduces dust dispersion without the need for a tarp. A sustainable and efficient solution for environmental control.';
$keywords = 'Water and Polymer Sprayer';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>DUST SUPPRESSION</b> - WATER AND POLYMER SPRAYER FOR TRUCK BUCKETS </h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJECTIVE:</h2>
                <p>The Semi-Gantry system is designed to inject water and polymer, forming a protective solution on the surface of truck loads. This eliminates the need for tarps and prevents dust dispersion into the environment.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/aspersor-de-agua-e-polimero-para-cacamba-de-caminhoes.jpg" class="img-responsive mx-" alt="Aspersor de água e polímero para caçamba de caminhões, solução para controle de poeira sem uso de lona.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">OPERATION:</h2>
                <p>The system can operate in conjunction with the washer, allowing simultaneous and integrated functionality.</p>
            </div>

            <!--<div class="image text-center mx-5 px-5">
                <img src="images/planta-projeto-despoeiramento-aspersao-em-vagoes-de-minerio.jpg" class="img-responsive mx-" alt="Despoeiramento - Aspersão em Vagões de Minério | Projeto para controle de poeira emitidos por vagões de minério.">
            </div>-->

        </div>
    </div>


    <!--<div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VANTAGENS:</h2>

                <ul class="list">
                    <li>Controle dos impactos ambientais;</li>
                    <li>Redução da perda de carga;</li>
                    <li>Baixo custo de operação;</li>
                    <li>Baixo custo de manutenção;</li>
                    <li>Evita o desperdício de água;</li>
                    <li>Remoção completa dos resíduos.</li>
                </ul>

                <br>

            </div>

            <div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/eMxKUJNbshI?si=TGmAqaoLDYXAFIAR"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>
        </div>
    </div>-->




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="en/contact/" target="_self" class="btn btn-more fs-2">REQUEST A CONTACT</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>