<?
$title = 'Ore Wagon Spraying | Dust Control with AsperWagon';
$description = 'Discover AsperWagon, the leading solution for ore wagon spraying. Control dust emissions, increase operational efficiency, and promote industrial sustainability.';
$keywords = 'Ore Wagon Spraying';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>DUST SUPPRESSION</b> - ORE WAGON SPRAYING | ASPERWAGON</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJECTIVE:</h2>
                <p>Reduce the loss of fine materials during rail transport and control particulate emissions along the railway.</p>

                <p>The water spraying system for ore wagons developed by Controlar is an automated system that sprays water and polymer to reduce fine material losses during rail transport and control particulate emissions along the railway.</p>
                
                <p>For the plant, we developed a spraying system that applies polymers with locking between wagons and flow interruption, ensuring that the solution does not spill onto the ground between the wagons or onto the locomotives.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/despoeiramento-aspersao-em-vagoes-de-minerio.jpg" class="img-responsive mx-" alt="Sistema AsperWagon de aspersão em vagões de minério para controle eficaz de poeira industrial.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">OPERATION:</h2>
                <p>The system is controlled by sensors and is fully automated. It controls the spraying of water onto the materials loaded in the wagons. By controlling the spraying time and water flow, it is capable of functioning at different train speeds.</p>
                
                <p>Controlar provides all the necessary engineering for the development, manufacturing, and supply of equipment.</p>
                
                <p>Sensors are installed to detect obstacles on the track, maintaining different heights to read the presence of locomotives or wagons. They also detect the gap between wagons. When an obstacle is detected, such as a shorter wagon or a taller locomotive, a signal is sent to the PLC.</p>
            </div>

            <div class="image text-center mx-5 px-5">
                <img src="images/planta-projeto-despoeiramento-aspersao-em-vagoes-de-minerio.jpg" class="img-responsive mx-" alt="Despoeiramento - Aspersão em Vagões de Minério | Projeto para controle de poeira emitidos por vagões de minério.">
            </div>

        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">ADVANTAGES:</h2>

                <ul class="list">
                    <li>Environmental impact control;</li>
                    <li>Reduction of load loss;</li>
                    <li>Low operating cost;</li>
                    <li>Low maintenance cost;</li>
                    <li>Prevents water waste;</li>
                    <li>Complete residue removal.</li>
                </ul>

                <br>

            </div>

            <div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/eMxKUJNbshI?si=TGmAqaoLDYXAFIAR"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="en/contact/" target="_self" class="btn btn-more fs-2">REQUEST A CONTACT</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>