<?
$title = 'Dust Suppression in Crushing | Efficient Dust Control - AsperBelt';
$description = 'Discover AsperBelt, a specialized solution for dust suppression in crushing operations. Reduce dust in industrial processes, enhancing efficiency and sustainability.';
$keywords = 'Dust Suppression in Crushing';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1>
            <b>DUST SUPPRESSION</b> - SPRAYING IN CRUSHING | ASPERBELT
        </h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJECTIVE:</h2>
                <p><strong>Dust suppression and particulate control</strong> in <strong>crushing conveyors</strong>, <strong>transfer points</strong> and other processes.</p>

                <p>The <strong>spraying system</strong> for haul roads and industrial pathways developed by Controlar is a fully automated system that controls particulate matter emissions in industrial transport routes.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/aspersao-em-correias-transportadora-de-britagem.jpg" class="img-responsive mx-" alt="AsperBelt Spraying System for Crushing Operations | Effective Dust Control in Industrial Environments.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">OPERATION:</h2>
                <p>The system sprays water using motor pumps without the need for compressors. The water is stored in a reservoir, and the system is controlled by sensors and automated triggers according to the client's desired programming. This system does not use detergents, surfactants, or any other chemicals.</p>
            </div>
        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">ADVANTAGES:</h2>

                <ul class="list">
                    <li>Environmental impact control;</li>
                    <li>Effective dust emission control;</li>
                    <li>Low operating cost;</li>
                    <li>Low maintenance cost;</li>
                    <li>Prevents water waste;</li>
                    <li>Complete residue removal;</li>
                    <li>Does not oversaturate the material.</li>
                </ul>

                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="en/contact/" target="_self" class="btn btn-more fs-2">REQUEST A CONTACT</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>