<?
$title = 'Ore Yard Spraying | High-Efficiency Dust Control';
$description = 'Ensure a cleaner and more sustainable environment with our ore yard spraying solution. Effective dust control for maximum operational efficiency.';
$keywords = 'Ore Yard Spraying';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1>
            <b>DUST SUPPRESSION</b> - ORE YARD SPRAYING
        </h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJECTIVE:</h2>
                <p>Dust suppression for large ore stockpiles to control fugitive dust emissions</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/despoeiramento-de-grandes-pilhas-de-minerio-aspermovel-para-controle-de-emissoes-fugitivas-de-poeira.jpg" class="img-responsive mx-" alt="Sistema de aspersão em pátio de minério para controle de poeira e sustentabilidade industrial.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">OPERATION:</h2>
                <p>This system allows for stops and reversals, optimizing energy consumption. It is ideal for reducing environmental impact, as it eliminates the need for water trucks, significantly saving water resources.</p>
            </div>
        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">ADVANTAGES:</h2>

                <ul class="list">
                    <li>Carbon steel piping;</li>
                    <li>Allows polymer application;</li>
                    <li>Smart automation system via PLC.</li>
                </ul>

                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="en/contact/" target="_self" class="btn btn-more fs-2">REQUEST A CONTACT</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>