<?
$title = 'Haul Road Spraying | Efficient Dust Control - AsperRoad';
$description = 'Discover AsperRoad, an innovative solution for haul road spraying. Reduce dust emissions, ensure sustainability, and enhance operational efficiency in your industry.';
$keywords = 'Haul Road Spraying';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>DUST SUPPRESSION</b> - SPRAYING ON HAUL ROADS OR INDUSTRIAL PATHWAYS | ASPERROAD</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJECTIVE:</h2>
                <p>Controlling particulate matter emissions on haul roads and industrial pathways.</p>

                <p>The haul road and industrial pathway spraying system developed by Controlar is an automated solution designed to control particulate matter emissions in these environments.</p>
                
                <p>This solution focuses on reducing investment costs, maintenance costs, and operational costs while maintaining the same quality and effectiveness required for airborne particulate containment.</p>
                
                <p>This system eliminates the need for water trucks for road wetting, making the proposed automated system highly effective and efficient.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/despoeiramento-aspersao-em-vias-ou-pista-de-rolamento-asperroad.jpg" class="img-responsive mx-" alt="Controlar a emissão de material particulado em vias e/ou estradas de rolamento.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">OPERATION:</h2>
                <p>The road humidification system consists of a water reservoir, a set of motor pumps, spray nozzles, and pipelines. It is fully automated through an electronic control unit. This system is highly efficient as it eliminates the need for water trucks, significantly reducing water and energy consumption, and consequently lowering operational costs.</p>
                
                <p>The sprayers operate independently, meaning each sector can be programmed separately. These are currently the most widely used sprayers in high-precision systems, ensuring that the system's flow rate always corresponds to the most effective and balanced condition. They allow for multiple activation points within a system, following the principle of efficient flow management. Additionally, they offer great flexibility to meet specific system needs.</p>
            </div>
        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">ADVANTAGES:</h2>

                <ul class="list">
                    <li>Environmental impact control;</li>
                    <li>Low operating cost;</li>
                    <li>Low maintenance cost;</li>
                    <li>Prevents water waste;</li>
                    <li>Complete control of particulate matter emissions during internal transport.</li>
                </ul>

                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="en/contact/" target="_self" class="btn btn-more fs-2">REQUEST A CONTACT</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>