<?
$title = 'Rental of Wheel and Chassis Washers and Dust Suppression Equipment';
$description = 'Rent wheel and chassis washers and dust suppression equipment. Complete solutions for dust control and industrial cleaning with efficiency and cost savings.';
$keywords = 'rental of wheel and chassis washers, rental of dust suppression equipment';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>RENTAL OF DUST SUPPRESSION EQUIPMENT</b> AND WHEEL AND CHASSIS WASHERS</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJECTIVE:</h2>
                <p>At <strong>Controlar Projects and Engineering</strong>, innovation and efficiency are our core values. We are the only company that sells and rents <strong>dust suppression equipment for ore transport roads and wheel and chassis washers</strong> developed in-house.</p>

                <p>Our dust suppression equipment for ore transport roads is the most advanced on the market, significantly reducing dust emissions and protecting both workers' health and the environment. Additionally, our wheel and chassis washers are highly effective in cleaning vehicles, reducing maintenance time and extending equipment lifespan.</p>
                
                <p>By choosing Controlar Projects and Engineering, you can be sure you are selecting quality and efficiency. Our equipment is designed and tested by the best engineers in the industry, and our technical support team is always ready to help you find the perfect solution for your needs.</p>
                
                <p>Stop wasting time and money on ineffective equipment. Contact us today and discover how our dust suppression equipment and wheel and chassis washers can transform your operation into a true success story.</p>
                
            </div>
        </div>
    </div>



    <!--<div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/despoeiramento-aspersao-em-vias-ou-pista-de-rolamento-asperroad.jpg" class="img-responsive mx-" alt="Controlar a emissão de material particulado em vias e/ou estradas de rolamento.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMENTO:</h2>
                <p>O sistema de umidificação de vias é composto por um reservatório de água, um conjunto de moto bombas, bicos aspersores e tubulações. Ele é automatizado por meio de uma central eletrônica. Este sistema é muito eficaz porque, já que evita o uso de caminhões pipa, sua utilização reduz o uso de recursos hídricos e de energia elétrica, reduzindo assim os custos operacionais.</p>
            </div>
        </div>
    </div>-->


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">ADVANTAGES:</h2>

                <ul class="list">
                    <li>Faster delivery time compared to purchasing equipment;</li>
                    <li>Rental contracts starting from 4 months;</li>
                    <li>Preventive and corrective maintenance included in the monthly fee;</li>
                    <li>Equipment mainly designed for mining and steel industries;</li>
                    <li>High-efficiency washers with significant water savings, recovering up to 90% compared to other market solutions;</li>
                    <li>Easy to operate and maintain;</li>
                    <li>Washers with a 5-year warranty.</li>
                </ul>

                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="en/contact/" target="_self" class="btn btn-more fs-2">REQUEST A CONTACT</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>