<?
$title = 'Controlar | Dust Suppression and Dust Control Solutions';
$description = 'Controlar provides dust suppression solutions for dust control in industries such as mining and steelmaking, promoting sustainability and efficiency.';
$keywords = 'dust suppression solutions';
include '_header.phtml';
?>

<main role="main">

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">

            <div class="carousel-item active" style="background-image: url('images/vitrine-lavador-rodas-01.jpg')" aria-label="Controlar Sistemas | Lavador de Rodas e Chassis;">
            </div>

            <div class="carousel-item" style="background-image: url('images/vitrine-locacao-equipamentos-estrada-de-rodagem-01.jpg')" aria-label="Controlar Sistemas | Equipment Rental for Road Spraying">
            </div>

            <!--<div class="carousel-item" style="background-image: url('images/example-image-slide.jpg');">
            </div>-->

        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>




    <div class="container contato pb-4">
        <h1><strong>Innovative Solutions</strong> in Dust Suppression and Dust Control.</h1>



        <form id="meuFormulario" action="_mailSender.php" method="POST">

            <h2>TALK TO ONE OF OUR SPECIALISTS.</h2>
            <h3><strong>REQUEST A QUOTE HERE!</strong></h3>

            <input type="text" name="nome" placeholder="Full Name *" required>
            <input type="email" name="email" placeholder="Email *" required>
            <input type="text" placeholder="Company Name *" name="empresa" required>
            <input type="tel" placeholder="Phone Number with Area Code *" name="telefone" required>

            <select id="produto" name="produto">
                <option value="" selected disabled>Which product are you interested in?</option>
                <option value="Dust Suppression in Truck Buckets">Dust Suppression in Truck Buckets</option>
                <option value="Dust Suppression on Haul Roads">Dust Suppression on Haul Roads</option>
                <option value="Dust Suppression in Ore Wagons">Dust Suppression in Ore Wagons</option>
                <option value="Dust Suppression in Ore Yards">Dust Suppression in Ore Yards</option>
                <option value="Wheel and Chassis Washer">Wheel and Chassis Washer</option>
                <option value="Dust Suppression in Crushing Plants">Dust Suppression in Crushing Plants</option>
                <option value="Equipment Rental">Equipment Rental</option>
            </select>

            <select id="como_conheceucomo_conheceu" name="como_conheceu">
                <option value="" selected disabled>How did you learn about Controlar?</option>
                <option value="Google Search">Google Search</option>
                <option value="On Linkedin">On Linkedin</option>
                <option value="On Instagram">On Instagram</option>
                <option value="On YouTube">On YouTube</option>
                <option value="At Trade Events">At Trade Events</option>
                <option value="Third-Party Recommendation">Third-Party Recommendation</option>
            </select>

            <div id="mensagemFeedback"></div>

            <input type="hidden" name="type" value="orcamento" />
            <input type="hidden" id="recaptchaToken" name="recaptchaToken" value="" />


            <div class="d-flex justify-content-between">
                <p>* All fields are required</p>
                <button type="submit" id="meuBotao">TALK TO A CONSULTANT</button>
            </div>
        </form>





    </div><!-- /.contato -->

    <!-- <div class="especialistas2 p-4 text-center">
            <h4>Somos especialistas <strong>em Despoeiramento.</strong></h4>
        </div> -->

    <div class="only-mobile p-4 text-center bg-white">
        <a href="#" class="btn btn-whatsapp">
            <img src="images/ico-whatsapp.png" alt=""> TALK TO A SPECIALIST
        </a>
    </div>


    <div class="container especialistas py-5 mt-5">

        <div class="row ">
            <div class="col-md-6">
                <h2>
                    Experts in Dust Suppression <br>
                    <strong>and Emission Control.</strong>

                    <div class="image-box my-3" aria-label="A specialized team in dust suppression developing solutions for industrial emission control with a focus on sustainability.;"></div>
                </h2>
            </div>
            <div class="col-md-6 d-flex flex-column justify-content-start">

                <p>The growing environmental concerns and commitment to sustainability across all industrial sectors have led to an increasing demand for effective solutions to control airborne particulate emissions resulting from production processes.</p>

                <p>CONTROLAR was founded to support companies seeking to minimize these emissions throughout their production chains. Our multidisciplinary team, composed of experienced managers and highly qualified engineers, develops innovative and fully automated projects. Our goal is to provide tailored solutions that ensure excellence, operational efficiency, and added value, meeting the specific needs of each client.</p>

            </div>
        </div>

    </div><!-- /.especialistas -->

    <div class="equipamentos pt-5">
        <div class="container">

            <h2>
                Our <br>
                <strong>Equipment and Services</strong>
            </h2>

            <p class="feature">We offer preventive and corrective maintenance for our projects.</p>


            <div id="myCarouselEquipamentos" class="carousel slide only-desktop" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#myCarouselEquipamentos" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarouselEquipamentos" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">

                    <!-- INICIO ITEM  -->
                    <div class="carousel-item active">
                        <div class="row">

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-aspersao-em-vagoes-de-minerio.jpg)" aria-label="Dust Suppression - Ore Wagon Spraying | Particulate Matter Emission Control Along Railways.;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">INNOVATIVE EQUIPMENT</div>
                                    <div class="title">DUST SUPPRESSION IN ORE WAGONS</div>
                                    <p>Reduce fine material losses during rail transport and control particulate matter emissions along the railway.</p>
                                    <div class="btn-box">
                                        <a href="en/dust-suppression-in-ore-wagons/" target="_self" class="text-uppercase btn-more">Learn More</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-aspersao-em-vias-ou-pista-de-rolamento-asperroad.jpg)" aria-label="Dust Suppression on Haul Roads and Industrial Pathways | AsperRoad.;">
                                    </div>
                                    <!--<div class="featured"><img src="images/ico-arrow.png" alt="">EQUIPAMENTO
                                        INOVADOR</div>-->
                                    <div class="title">DUST SUPPRESSION ON HAUL ROADS AND INDUSTRIAL PATHWAYS</div>
                                    <p>AsperRoad provides dust suppression on haul roads and industrial pathways by controlling particulate matter emissions.</p>
                                    <div class="btn-box">
                                        <a href="en/dust-suppression-on-haul-roads" target="_self" class="text-uppercase btn-more">Learn More</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-de-grandes-pilhas-de-minerio-aspermovel-para-controle-de-emissoes-fugitivas-de-poeira.jpg)" aria-label="Dust Suppression for Large Ore Stockpiles | Aspermóvel;">
                                    </div>
                                    <!--<div class="featured"><img src="images/ico-arrow.png" alt="">Sistema inédito!
                                    </div>-->
                                    <div class="title">DUST SUPPRESSION FOR ORE STOCKPILES</div>
                                    <p>Dust suppression for ore stockpiles to control fugitive dust emissions.</p>
                                    <div class="btn-box">
                                        <a href="/en/dust-suppression-in-ore-yards" target="_self" class="text-uppercase btn-more">Learn More</a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <!-- FIM ITEM -->

                    <!-- INICIO ITEM  -->
                    <div class="carousel-item">
                        <div class="row">

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/eliminar-poeira-lavador-de-rodas.jpg)" aria-label="Wheel Washer - Automatic Cleaning System for Complete Residue Removal | AsperWash;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">INNOVATIVE SYSTEM!
                                    </div>
                                    <div class="title">WHEEL AND CHASSIS WASHER</div>
                                    <p>AsperWash is an automatic cleaning system that ensures complete residue removal through high-pressure water spraying.</p>
                                    <div class="btn-box">
                                        <a href="/en/wheel-and-chassis-washer" target="_self" class="text-uppercase btn-more">Learn More</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/aspersao-em-correias-transportadora-de-britagem.jpg)" aria-label="Dust Suppression on Crushing Conveyor Belts | AsperBelt;">
                                    </div>

                                    <div class="title">DUST SUPPRESSION SOLUTION FOR CRUSHING OPERATIONS</div>
                                    <p>AsperBelt provides dust suppression and particulate control for crushing conveyors, transfer points, and conveyor belts.</p>
                                    <div class="btn-box">
                                        <a href="/en/dust-suppression-in-crushing-plants" target="_self" class="text-uppercase btn-more">Learn More</a>
                                    </div>
                                </div>
                            </div>

                            <!--<div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>

                                    <div class="title">Quos sequi voluptatem #2 </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" target="_self" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>-->
                        </div>
                    </div>
                    <!-- FIM ITEM -->


                </div>
                <a class="carousel-control-prev" href="#myCarouselEquipamentos" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#myCarouselEquipamentos" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>


            <div id="myCarouselEquipamentosMobile" class="carousel slide only-mobile" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="1"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="2"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="3"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="4"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="5"></li>
                </ol>
                <div class="carousel-inner">

                    <div class="carousel-item active">

                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-aspersao-em-vagoes-de-minerio.jpg)" aria-label="Dust Suppression - Ore Wagon Spraying | Particulate Emission Control Along Railways;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">INNOVATIVE EQUIPMENT</div>
                                    <div class="title">ORE WAGON SPRAYING</div>
                                    <p>Reduce fine material losses during rail transport and control particulate matter emissions along the railway with our advanced ore wagon spraying system.</p>
                                    <div class="btn-box">
                                        <a href="/en/dust-suppression-in-ore-wagons" target="_self" class="text-uppercase btn-more">Learn More</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-aspersao-em-vias-ou-pista-de-rolamento-asperroad.jpg)" aria-label="Dust Suppression on Haul Roads and Industrial Pathways | AsperRoad.;">
                                    </div>

                                    <div class="title">DUST SUPPRESSION ON HAUL ROADS AND INDUSTRIAL PATHWAYS</div>
                                    <p>AsperRoad provides effective dust suppression on haul roads and industrial pathways by controlling particulate matter emissions.</p>
                                    <div class="btn-box">
                                        <a href="/en/dust-suppression-on-haul-roads" target="_self" class="text-uppercase btn-more">Learn More</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="row">
                            <div class="col-md-4">

                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-de-grandes-pilhas-de-minerio-aspermovel-para-controle-de-emissoes-fugitivas-de-poeira.jpg)" aria-label="Dust Suppression for Large Ore Stockpiles | Aspermóvel;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">INNOVATIVE SYSTEM!
                                    </div>
                                    <div class="title">DUST SUPPRESSION FOR ORE STOCKPILES</div>
                                    <p>Automatic dust suppression system (Aspermóvel) designed for controlling fugitive dust emissions from large ore stockpiles.</p>
                                    <div class="btn-box">
                                        <a href="/en/dust-suppression-in-ore-yards" target="_self" class="text-uppercase btn-more">Learn More</a>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/eliminar-poeira-lavador-de-rodas.jpg)" aria-label="Wheel Washer - Automatic Cleaning System for Complete Residue Removal | AsperWash;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">INNOVATIVE SYSTEM!</div>
                                    <div class="title">WHEEL AND CHASSIS WASHER</div>
                                    <p>AsperWash is an automatic cleaning system that ensures complete residue removal through high-pressure water spraying.</p>
                                    <div class="btn-box">
                                        <a href="/en/wheel-and-chassis-washer" target="_self" class="text-uppercase btn-more">Learn More</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/aspersao-em-correias-transportadora-de-britagem.jpg)" aria-label="Dust Suppression on Crushing Conveyor Belts | AsperBelt;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">INNOVATIVE SYSTEM!
                                    </div>
                                    <div class="title">DUST SUPPRESSION SOLUTION FOR CRUSHING OPERATIONS</div>
                                    <p>AsperBelt provides efficient dust suppression and particulate control for crushing conveyors, transfer points, and conveyor belts.</p>
                                    <div class="btn-box">
                                        <a href="/en/dust-suppression-in-crushing-plants" target="_self" class="text-uppercase btn-more">Learn More</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--<div class="carousel-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>

                                    <div class="title">Quos sequi voluptatem #2 </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" target="_self" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>-->



                </div>
                <a class="carousel-control-prev" href="#myCarouselEquipamentosMobile" role="button"
                    data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#myCarouselEquipamentosMobile" role="button"
                    data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>



        </div>
    </div><!-- /.equipamentos -->

    <div class="bg-white p-4 only-mobile">
        <div class="col-md-12">
            <a href="#" class="text-uppercase btn-more">See More Products</a>
        </div>
    </div>

    <div class="container py-5 text-center clientes">
        <h2>Some <strong>of Our Clients</strong></h2>

        <div class="w-100 flex justify-content-center align-items-center">
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-vale.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-anglo.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-csn.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-votorantim.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-inb.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-alcoa.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-avante.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-mrs.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-itaminas.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-groupmoura.png" alt=""></a>
        </div>

    </div><!-- /.clientes -->

</main>

<? include '_footer.phtml'; ?>