<?
$title = 'Innovative Dust Suppression Projects | Custom Solutions by Controlar';
$description = 'Explore innovative dust suppression projects developed by Controlar. Discover customized and efficient solutions for industrial dust control.';
$keywords = 'innovative dust suppression projects';
include '_header.phtml';
?>


<main role="main" class="internal">


    <div class="breadcrumb container">
        <h1><b>INNOVATIVE PROJECTS</b></h1>
    </div>

    <div class="bg-white">

        <div class="container projetos">

            <h3 class="text-center py-5">Get to know some of our innovative projects</h3>


            <!-- Item -->
            <div class="bg-silver"></div>
            <div class="z-100">

                <div class="px-5">
                    <h2 class="pt-4 pb-3 px-5">Aspermóvel | Mobile Solution for Dust Control</h2>
                    <p class="px-5">Discover Aspermóvel, a mobile and innovative solution for dust suppression and control. Ideal for ore yards, haul roads, and environments that require operational flexibility.</p>
                </div>

                <div class="youtube-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/2tMY9oX7T1Q?si=IOgRkqdtZr4UUd9_"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>


            <!-- Item -->
            <div class="bg-silver"></div>
            <div class="z-100">

                <div class="px-5">
                    <h2 class="pt-4 pb-3 px-5">AsperWagon | Ore Wagon Spraying</h2>
                    <p class="px-5">See AsperWagon in action, ensuring efficient dust control in ore wagons with advanced technology and sustainable results.</p>
                </div>


                <div class="youtube-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/Bwacn0D1x2M?feature=oembed"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>


            <!-- Item -->
            <div class="bg-silver"></div>
            <div class="z-100">

                <div class="px-5">
                    <h2 class="pt-4 pb-3 px-5">AsperWash | Innovative Wheel and Chassis Washing System</h2>
                    <p class="px-5">Discover AsperWash, an efficient solution for wheel and chassis washing in industrial environments. Reduce residues and ensure cleaning with sustainability and high performance.</p>
                </div>


                <div class="youtube-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>

        </div>


        <div class="pb-5 text-center">
            <a href="en/contact/" target="_self" class="btn btn-more fs-2 w-400">QUESTIONS? REQUEST A CONTACT</a>
        </div>

    </div>

</main>


<? include '_footer.phtml'; ?>