<?
$title = 'Wheel and Chassis Washer | Efficient Vehicle Cleaning';
$description = 'Discover Controlar’s Wheel and Chassis Washer. An effective solution for vehicle cleaning, ensuring efficiency, safety, and sustainability.';
$keywords = 'Wheel and Chassis Washer';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>DUST SUPPRESSION</b> - WHEEL AND CHASSIS WASHER</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJECTIVE:</h2>
                <p>Eliminate dust and other residues inherent to land transportation.</p>

                <p>The chassis washer developed by Controlar is an automatic cleaning system that ensures the complete removal of residues through high-pressure water spraying. The washers are designed to clean the underside of vehicle chassis as well as the tires.</p>

                <p>The system is also capable of washing all types of road vehicles and is built in compliance with Brazilian standards.</p>
                
                <p>To achieve this goal, we propose the installation of a washing system that distributes water through high-pressure spray nozzles, ensuring a uniform cleaning process across the vehicle’s surface. This process effectively reduces or eliminates residues that could be transported and deposited along external roads.</p>
            </div>
        </div>
    </div>

    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/eliminar-poeira-lavador-de-rodas.jpg" class="img-responsive mx-" alt="Lavador de rodas e de chassi para limpeza eficiente de veículos industriais e controle de resíduos e de poeira.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">OPERATION:</h2>
                <p>The system is controlled by sensors and is fully automated. It allows water to circulate in a controlled manner, either in a closed or full circuit.</p>
                
                <p>This system is designed to wash tires and the underside of truck and machinery chassis. The wheel and chassis washer is already in operation at mining sites, industrial plants, and ports, efficiently removing all material adhered to these vehicles.</p>
                
                <p>The entire washing process is automatic, managed by sensors that control vehicle entry and exit. As water jets are sprayed through the nozzles, dirt is washed away through a grated drainage system, effectively removing all impurities from the tires and chassis. The removed residues are collected at the bottom of the washer and transported directly to decantation tanks (concrete) with an oil separator or directed to a designated waste area.</p>
            </div>
        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">ADVANTAGES:</h2>

                <ul class="list">
                    <li>Environmental impact control;</li>
                    <li>Low operating cost;</li>
                    <li>Low maintenance cost;</li>
                    <li>Prevents water waste;</li>
                    <li>Complete residue removal.</li>
                </ul>

                <br>

                <h2 class="big">APPLICATIONS:</h2>

                <ul class="list">
                    <li>Exit access points of various industrial plants (mining, cement, steel, etc.);</li>
                    <li>Internal areas of various industrial plants;</li>
                    <li>Ports.</li>
                </ul>

                <br>
                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="en/contact/" target="_self" class="btn btn-more fs-2">REQUEST A CONTACT</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>