<?
$title = 'Página não encontrada (404)';
$description = 'Página não encontrada (404)';
$keywords = '';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <b>404</b> - PÁGINA NÃO ENCONTRADA
    </div>

    <div class="bg-silver">
        <div class="container p-5 solucoes">

            <div class=" mx-5 px-5">

                <p>Parece que você se perdeu...</p>
                <p>A página que você está tentando acessar não existe ou foi movida.</p>
                <p>Não se preocupe, aqui estão algumas opções para continuar navegando:</p>
                <ul>
                    <li><a href="./">Voltar para a página inicial</a></li>
                    <li><a href="contato/">Entre em contato conosco</a></li>
                </ul>
                <p>Se você acredita que isso é um erro, entre em contato com o suporte técnico.</p>
            </div>
        </div>
    </div>


</main>

<? include '_footer.phtml'; ?>