<!-- FOOTER -->

<footer class="pt-4 pb-0">

    <div class="text-center brand">
        <a href="./">
            <img src="images/controlar-logo-black.png" alt="">
        </a>
    </div>

    <div class="only-mobile container text-white text-center">

        <h3 class="">Por meio da tecnologia, buscamos apresentar aos clientes soluções inovadoras para reduzir os impactos ambientais e promover a sustentabilidade.</h4>

            <a href="#" class="btn btn-whatsapp my-4">
                <img src="images/ico-whatsapp.png" alt=""> FALE COM UM ESPECIALISTA
            </a>

            <a href="#" target="_blank" class="btn btn-youtube my-4">
                <img src="images/ico-youtube-white.png" alt="">
            </a><br>
    </div>

    <div class="menu container d-flex justify-content-between">

        <!-- Links principais -->
        <section>
            <ul style=" list-style-type: none; padding: 0;">
                <li><a href="despoeiramento/">O que é Despoeiramento?</a></li>
                <li><a href="quem-somos/">Quem Somos</a></li>
                <li><a href="clientes-parceiros/">Clientes e Parceiros</a></li>
                <li><a href="fale-conosco/">Fale Conosco</a>
                </li>
            </ul>
        </section>

        <!-- Serviços de aspersão -->
        <section>
            <ul style="list-style-type: none; padding: 0;">
                <li><a href="vias-rolamento/">Aspersão em Vias de Rolamento</a></li>
                <li><a href="vagoes-minerio/">Aspersão em Vagões de Minério</a></li>
                <li><a href="patios-minerio/">Aspersão em Pátios de Minério</a></li>
                <li><a href="lavador-rodas-chassi/">Lavador de Rodas e de Chassi</a></li>
                <li><a href="aspersao-britagens/">Aspersão em Britagens</a></li>
            </ul>
        </section>

        <section class="social">
            SIGA-NOS EM NOSSAS<br> REDES SOCIAIS<br>
            <a href="#" target="_blank"><img src="images/ico-youtube.png" class="zoom" alt=""></a>
        </section>


    </div>
    <div class="sign">
        <div class="container">
            <a href="https://agenciadecriacao.com.br" target="_blank">
                <img src="images/agencia-criacao.png" alt="">
            </a>
        </div>
    </div>

</footer><!-- /.FOOTER -->


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script>
    window.jQuery || document.write('<script src="/assets/js/vendor/jquery-slim.min.js"><\/script>')
</script>
<script src="/dist/js/bootstrap.bundle.min.js?v=2"
    integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o"
    crossorigin="anonymous"></script>

</body>

</html>