<!doctype html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="<?= $description; ?>">
    <meta name="keywords" content="<?= $keywords; ?>">

    <meta name="author" content="Brainatwork TI">


    <?php
    $currentUrl = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://" . $_SERVER['HTTP_HOST'];
    echo '<base href="' . $currentUrl . '" target="_blank">';
    ?>

    <title><?= $title; ?></title>


    <!-- Bootstrap core CSS -->
    <link href="/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
        rel="stylesheet">

    <link href="css/main.css?v4=true<?= date("Hisdmy"); ?>" rel="stylesheet">

    <!-- Favicon -->
    <link rel="icon" href="images/favicon-32x32.png" sizes="32x32" />

</head>

<body>
    <header>



        <nav class="navbar navbar-expand-md container p-0">

            <div class="dd-flex w-100">
                <div>
                    <a class="navbar-brand " href="./">
                        <img src="images/controlar-logo.png" class="only-desktop" alt="">
                        <img src="images/controlar-logo-mobile.png" class="only-mobile" alt="">
                    </a>
                </div>

                <div class="flex-grow-1 d-flex flex-column justify-content-between">

                    <div class="social-links w-100 d-flex justify-content-between align-items-center">

                        <a href="mailto: comercial@controlarsistemas.com" class="zoom"> <img src="images/ico-emaill.png" alt="">
                            comercial@controlarsistemas.com
                        </a>
                        <a href="#" class="zoom"> <img src="images/ico-time.png" alt="">
                            De seg. a sex., das 8h às 18h.
                        </a>
                        <a href="https://youtube.com" class="zoom" target="_blank"> <img src="images/ico-youtube.png" alt="">
                            Acesse nosso Youtube
                        </a>

                        <div class="flags">
                            <a href="#"><img class="zoom" src="images/flag-brasil.png" alt=""></a><a href="#"><img class="zoom"
                                    src="images/flag-eua.png" alt=""></a><a href="#"><img class="zoom" src="images/flag-spain.png"
                                    alt=""></a>
                        </div>
                    </div>


                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <div class="line"></div>
                        <div class="line"></div>
                        <div class="line"></div>
                    </button>


                    <div class="collapse navbar-collapse align-items-end justify-content-between flex-grow-1"
                        id="navbarCollapse">
                        <ul class="navbar-nav justify-content-between d-flex flex-grow-1">

                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link menu-item dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">Soluções</a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="aspersao-em-vias/">ASPERSÃO EM VIAS DE
                                        ROLAMENTO</a>
                                    <a class="dropdown-item" href="aspersao-em-vias/">ASPERSÃO EM VAGÕES DE
                                        MINÉRIO</a>
                                    <a class="dropdown-item" href="aspersao-em-vias/">ASPERSÃO EM PÁTIOS DE
                                        MINÉRIO</a>
                                    <a class="dropdown-item" href="aspersao-em-vias/">LAVADOR DE RODAS E DE
                                        CHASSI</a>
                                    <a class="dropdown-item" href="aspersao-em-vias/">ASPERSÃO EM BRITAGENS</a>
                                    <a class="dropdown-item" href="aspersao-em-vias/">LOCAÇÃO DE EQUIPAMENTOS</a>
                                </div>
                            </li>


                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link menu-item dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">Projetos</a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> <a
                                        class="dropdown-item" href="projetos-inovadores/">PROJETOS INOVADORES</a>
                                    <a class="dropdown-item" href="projetos-inovadores/">PROJETOS EXECUTADOS</a>
                                </div>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="despoeiramento/">Despoeiramento</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="clientes/">Clientes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="quem-somos/">Quem Somos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="contato/">Contato</a>
                            </li>


                        </ul>
                    </div>

                </div>

            </div>




        </nav>
    </header>


    <!-- HEADER end -->