<?
$title = 'Aspersão em Pátio de Minério | Controle de Poeira com Alta Eficiência';
$description = 'Garanta um ambiente mais limpo e sustentável com nossa solução de aspersão em pátio de minério. Controle eficaz de poeira para máxima eficiência operacional.';
$keywords = 'Aspersão em Pátio de Minério';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1>
            <b>DESPOEIRAMENTO</b> - ASPERSÃO EM PÁTIO DE MINÉRIO
        </h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p>Despoeiramento de grandes pilhas de minérios para controle de emissões fugitivas de poeira.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/despoeiramento-de-grandes-pilhas-de-minerio-aspermovel-para-controle-de-emissoes-fugitivas-de-poeira.jpg" class="img-responsive mx-" alt="Sistema de aspersão em pátio de minério para controle de poeira e sustentabilidade industrial.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMENTO:</h2>
                <p>Este sistema permite parada e reversões, economiza energia e é ideal para a redução do impacto ambiental, já que torna desnecessário o uso de caminhões pipa, economizando uma grande quantidade de água.</p>
            </div>
        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VANTAGENS:</h2>

                <ul class="list">
                    <li>Tubulação em aço carbono;</li>
                    <li>Permite a aplicação de polímeros;</li>
                    <li>Sistema de automação inteligente via PLC.</li>
                </ul>

                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="contato/" target="_self" class="btn btn-more fs-2">SOLICITE UM CONTATO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>