<?
$title = 'Soluções em Despoeiramento, Aspersão em Vagões de Minério, Vias e Pista de Rolamento, Abatimento de Pó e Abatimento de Poeira';
$description = 'Coloque a descricao aqui';
$keywords = 'teste1, teste2, teste3';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <b>DESPOEIRAMENTO</b> - ASPERSÃO EM VAGÕES DE MINÉRIO - ASPERWAGON
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h1>OBJETIVO:</h1>
                <p>Reduzir as perdas dos materiais finos durante o transporte ferroviário e controlar a emissão de
                    material particulado ao longo da ferrovia.</p>
                <p>O sistema de aspersão de água em vagões desenvolvido pela Controlar é um sistema automático de
                    jateamento de água e de polímero que promove a redução das perdas dos materiais finos durante o
                    transporte ferroviário e o controle das emissões de materiais particulados ao longo da ferrovia.
                </p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/example-image-slide.jpg" class="img-responsive mx-" alt="">
            </div>

            <div class=" mx-5 p-5">
                <h1>FUNCIONAMENTO:</h1>
                <p>O sistema é controlado por sensores e é totalmente automatizado. Ele controla a aspersão de água
                    sobre os materiais carregados pelos vagões. Por meio do controle de tempo de aspersão e do fluxo
                    de água de aspersão, ele é capaz de funcionar para diferentes velocidades de composição.</p>
            </div>
        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h1>VANTAGENS:</h1>

                <ul class="list">
                    <li>Controle dos impactos ambientais;</li>
                    <li>Redução da perda de carga;</li>
                    <li>Baixo custo de operação;</li>
                    <li>Baixo custo de manutenção;</li>
                    <li>Evita o desperdício de água;</li>
                    <li>Remoção completa dos resíduos.</li>
                </ul>

                <br>

            </div>

            <div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href=" #" class="btn btn-more fs-2">SOLICITE UM CONTATO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>