<?
$title = 'Aspersão em Britagem | Controle de Poeira com Eficiência - AsperBelt';
$description = 'Conheça o AsperBelt, solução especializada em aspersão em britagem. Reduza poeira no processo industrial, promovendo eficiência e sustentabilidade.';
$keywords = 'Aspersão em Britagem';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1>
            <b>DESPOEIRAMENTO</b> - ASPERSÃO EM BRITAGEM | ASPERBELT
        </h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p><strong>Supressão de poeira e abatimento de pó</strong> em <strong>transportadoras de britagem</strong>, em <strong>correias transportadoras</strong> e de transferência, dentre outros processos.</p>

                <p>O <strong>sistema de aspersão</strong> em vias e/ou pistas de rolamento desenvolvido pela Controlar é um sistema automático que controla a emissão de material particulado em vias ou pistas de rolamento industriais.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/aspersao-em-correias-transportadora-de-britagem.jpg" class="img-responsive mx-" alt="Sistema AsperBelt de aspersão em britagem para controle eficaz de poeira no ambiente industrial.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMENTO:</h2>
                <p>O sistema promove a aspersão de água por meio de moto bombas sem a necessidade de compressores. A água fica armazenada em um reservatório e o sistema é controlado por meio de sensores e acionamentos automáticos de acordo com a programação desejada pelo cliente. Este sistema não utiliza detergentes, tensoativos ou outros produtos químicos.</p>
            </div>
        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VANTAGENS:</h2>

                <ul class="list">
                    <li>Controle dos impactos ambientais;</li>
                    <li>Controle da emissão de poeira;</li>
                    <li>Baixo custo de operação;</li>
                    <li>Baixo custo de manutenção;</li>
                    <li>Evita o desperdício de água;</li>
                    <li>Remoção completa dos resíduos;</li>
                    <li>Não encharca o material.</li>
                </ul>

                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="contato/" target="_self" class="btn btn-more fs-2">SOLICITE UM CONTATO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>