<?
$title = 'Aspersão em Vagões de Minério | Controle de Poeira com AsperWagon';
$description = 'Descubra o AsperWagon, a solução líder em aspersão em vagões de minério. Controle emissões de poeira, aumente a eficiência operacional e promova a sustentabilidade industrial.';
$keywords = 'Aspersão em Vagões de Minério';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>DESPOEIRAMENTO</b> - ASPERSÃO EM VAGÕES DE MINÉRIO | ASPERWAGON</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p>Reduzir as perdas dos materiais finos durante o transporte ferroviário e controlar a emissão de material particulado ao longo da ferrovia.</p>

                <p>O sistema de aspersão de água em vagões desenvolvido pela Controlar é um sistema automático de jateamento de água e de polímero que promove a redução das perdas dos materiais finos durante o transporte ferroviário e o controle das emissões de materiais particulados ao longo da ferrovia.</p>
                
                <p>Para a planta desenvolvemos um sistema de aspersão com aplicação de polímeros com travamento entre vagões e interrupção do fluxo de forma que evitará que caia solução no chão entre os intervalos dos vagões tanto quanto sobre as locomotivas.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/despoeiramento-aspersao-em-vagoes-de-minerio.jpg" class="img-responsive mx-" alt="Sistema AsperWagon de aspersão em vagões de minério para controle eficaz de poeira industrial.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMENTO:</h2>
                <p>O sistema é controlado por sensores e é totalmente automatizado. Ele controla a aspersão de água sobre os materiais carregados pelos vagões. Por meio do controle de tempo de aspersão e do fluxo de água de aspersão, ele é capaz de funcionar para diferentes velocidades de composição.</p>
                
                <p>A Controlar fornece toda a engenharia necessária ao desenvolvimento na fabricação e fornecimento dos equipamentos.</p>
                
                <p>Os sensores são instalados para detecção de obstáculos sobre a linha mantendo alturas distintas para leem presença de locomotiva ou vagão. Também detectam o intervalo entre os vagões. A leitura de obstáculos, seja vagão pela altura menor ou locomotiva por maior altura, um sinal é comandado ao PLC.</p>
            </div>

            <div class="image text-center mx-5 px-5">
                <img src="images/planta-projeto-despoeiramento-aspersao-em-vagoes-de-minerio.jpg" class="img-responsive mx-" alt="Despoeiramento - Aspersão em Vagões de Minério | Projeto para controle de poeira emitidos por vagões de minério.">
            </div>

        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VANTAGENS:</h2>

                <ul class="list">
                    <li>Controle dos impactos ambientais;</li>
                    <li>Redução da perda de carga;</li>
                    <li>Baixo custo de operação;</li>
                    <li>Baixo custo de manutenção;</li>
                    <li>Evita o desperdício de água;</li>
                    <li>Remoção completa dos resíduos.</li>
                </ul>

                <br>

            </div>

            <div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/eMxKUJNbshI?si=TGmAqaoLDYXAFIAR"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="contato/" target="_self" class="btn btn-more fs-2">SOLICITE UM CONTATO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>