<?
$title = 'Aspersão em Vias de Rolamento | Controle de Poeira com Eficiência - AsperRoad';
$description = 'Conheça a AsperRoad, solução inovadora em aspersão em vias de rolamento. Reduza emissões de poeira, garanta sustentabilidade e eficiência operacional em sua indústria.';
$keywords = 'Aspersão em Vias de Rolamento';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>DESPOEIRAMENTO</b> - ASPERSÃO EM VIAS OU PISTA DE ROLAMENTO | ASPERROAD</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p>Controlar a emissão de material particulado em vias e/ou estradas de rolamento.</p>

                <p>O sistema de aspersão em vias e/ou pistas de rolamento desenvolvido pela Controlar é um sistema automático que controla a emissão de material particulado em vias ou pistas de rolamento industriais.</p>
                
                <p>Essa solução foca na redução do custo do investimento, na  redução dos custos de manutenção e na redução dos custos de operação mantendo a mesma qualidade e efetividade da necessidade técnica de contenção dos particulados suspensos.</p>
                
                <p>Este sistema consiste na eliminação de caminhões pipa para umectação de vias, sendo notoriamente eficaz e eficiente o sistema automatizado proposto.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/despoeiramento-aspersao-em-vias-ou-pista-de-rolamento-asperroad.jpg" class="img-responsive mx-" alt="Controlar a emissão de material particulado em vias e/ou estradas de rolamento.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMENTO:</h2>
                <p>O sistema de umidificação de vias é composto por um reservatório de água, um conjunto de moto bombas, bicos aspersores e tubulações. Ele é automatizado por meio de uma central eletrônica. Este sistema é muito eficaz porque, já que evita o uso de caminhões pipa, sua utilização reduz o uso de recursos hídricos e de energia elétrica, reduzindo assim os custos operacionais.</p>
                
                <p>Os aspersores possuem comando e acionamento independente, ou seja, cada setor é independente, podendo receber uma programação específica. Atualmente são os aspersores mais utilizados em sistemas de alta precisão. Eles permitem que a vazão de trabalho do sistema seja sempre correspondente à condição mais eficaz e equilibrada. Com eles, conseguimos fazer acionamentos em vários pontos diferentes de um sistema, adotando o princípio de manejo eficiente da vazão. Permite ainda uma grande flexibilidade no atendimento das necessidades pontuais do sistema.</p>
            </div>
        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VANTAGENS:</h2>

                <ul class="list">
                    <li>Controle dos impactos ambientais;</li>
                    <li>Baixo custo de operação;</li>
                    <li>Baixo custo de manutenção;</li>
                    <li>Evita o desperdício de água;</li>
                    <li>Controle completo da emissão de material particulado durante o transporte interno.</li>
                </ul>

                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="contato/" target="_self" class="btn btn-more fs-2">SOLICITE UM CONTATO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>