<?
$title = 'Aspersor de Água e Polímero para Caçamba de Caminhões | Controle de Poeira Eficiente';
$description = 'O Aspersor de Água e Polímero para Caçamba de Caminhões reduz a dispersão de poeira sem necessidade de lona. Solução sustentável e eficiente para controle ambiental.';
$keywords = 'Aspersor de Água e Polímero';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>DESPOEIRAMENTO</b> - ASPERSOR DE ÁGUA E POLIMERO PARA CAÇAMBA DE CAMINHÕES</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p>O Semipórtico é um sistema desenvolvido para injetar água e polímero formando uma solução protetora nas superfícies das pilhas nos caminhões sem a necessidade de colocar lona e evitar a propagação de poeira ao meio ambiente.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/aspersor-de-agua-e-polimero-para-cacamba-de-caminhoes.jpg" class="img-responsive mx-" alt="Aspersor de água e polímero para caçamba de caminhões, solução para controle de poeira sem uso de lona.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMENTO:</h2>
                <p>O funcionamento poderá ser conjugado e simultâneo com o lavador.</p>
            </div>

            <!--<div class="image text-center mx-5 px-5">
                <img src="images/planta-projeto-despoeiramento-aspersao-em-vagoes-de-minerio.jpg" class="img-responsive mx-" alt="Despoeiramento - Aspersão em Vagões de Minério | Projeto para controle de poeira emitidos por vagões de minério.">
            </div>-->

        </div>
    </div>


    <!--<div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VANTAGENS:</h2>

                <ul class="list">
                    <li>Controle dos impactos ambientais;</li>
                    <li>Redução da perda de carga;</li>
                    <li>Baixo custo de operação;</li>
                    <li>Baixo custo de manutenção;</li>
                    <li>Evita o desperdício de água;</li>
                    <li>Remoção completa dos resíduos.</li>
                </ul>

                <br>

            </div>

            <div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/eMxKUJNbshI?si=TGmAqaoLDYXAFIAR"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>
        </div>
    </div>-->




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="contato/" target="_self" class="btn btn-more fs-2">SOLICITE UM CONTATO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>