<?
$title = 'Soluções em Despoeiramento, Aspersão em Vagões de Minério, Vias e Pista de Rolamento, Abatimento de Pó e Abatimento de Poeira';
$description = 'Coloque a descricao aqui';
$keywords = 'teste1, teste2, teste3';
include '_header.phtml';
?>

<main role="main" class="internal">


    <div class="breadcrumb container">
        <h1><b>Nossos clientes e parceiros</b></h1>
    </div>

    <div class="bg-white ">

        <div class="container py-5 text-center clientes">


            <div class="w-100 flex justify-content-center align-items-center">
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-vale.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-anglo.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-csn.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-votorantim.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-inb.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-alcoa.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-avante.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-mrs.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-itaminas.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-groupmoura.png" alt=""></a>
            </div>

        </div>



    </div><!-- /.clientes -->



    <div class="p-5 text-center">
        <a href=" #" class="btn btn-more fs-2">SOLICITE UM CONTATO</a>
    </div>

</main>


<? include '_footer.phtml'; ?>