<?
$title = 'Entre em Contato | Solução para o Controle de Emissão de Poeira';
$description = 'Fale com a Controlar e descubra a solução ideal para o controle de emissão de poeira em sua indústria. Suporte especializado e atendimento personalizado.';
$keywords = 'solução para o controle de emissão de poeira';
include '_header.phtml';
?>

<main role="main" class="internal">


    <div class="breadcrumb container">
        <h1><b>Contato</b></h1>
    </div>

    <div class="relative h-10">
        <div class="bg-white max-height-500"></div>
    </div>

    <div class="container contato px-5 pb-5">

        <div class="box">
            <h1 class="px-3"><strong>Temos a melhor solução</strong> para o controle de emissão de poeira!</h1>


            <form action="#" method="POST">

                <h2>SOLICITE AQUI UM CONTATO COMERCIAL</h2>
                <h3><strong>COM UM DE NOSSOS ESPECIALISTAS!</strong></h3>

                <input type="text" name="nome" placeholder="Nome Completo *" required>
                <input type="email" name="email" placeholder="E-mail *" required>
                <input type="text" placeholder="Nome da Empresa *" name="empresa" required>
                <input type="tel" placeholder="Telefone com DDD *" name="telefone" required>

                <select id="produto" name="produto">
                    <option value="" selected disabled>Qual produto você tem interesse?</option>
                    <option value="produto1">Aspersão em Vias de Rolamento</option>
                    <option value="produto2">Aspersão em Vagões de Minério</option>
                    <option value="produto3">Aspersão em Pátios de Minério</option>
                    <option value="produto4">Lavador de Rodas e de Chassi</option>
                    <option value="produto5">Aspersão em Britagens</option>
                    <option value="produto6">Locação de Equipamentos</option>
                </select>

                <input type="tel" placeholder="Como conheceu a controlar? *" name="como_conheceu" required>

                <textarea name="texto"
                    placeholder="Detalhe aqui o seu projeto, como os problemas vivenciados e as sua necessidades. Iremos fazer um contato o mais breve possível"
                    id=""></textarea>

                <div class="d-flex justify-content-between">
                    <p>* Todos os campos são obrigatórios</p>
                    <button type="submit">FALE COM O CONSULTOR</button>
                </div>
            </form>
        </div>


    </div><!-- /.contato -->


</main>


<? include '_footer.phtml'; ?>