<?
$title = 'Despoeiramento | Soluções Eficientes para Controle de Poeira';
$description = 'Descubra as melhores soluções em despoeiramento com a Controlar. Controle de poeira eficiente e sustentável para diversos setores industriais.';
$keywords = 'despoeiramento';
include '_header.phtml';
?>

<main role="main" class="internal">


    <div class="breadcrumb container">
        <h1><b>DESPOEIRAMENTO</b></h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 despoeiramento">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">O que é poeira?</h2>
                <p><b>Poeira</b> ou <b>pó</b> são pequenas partículas de origens diversas, com estruturas e
                    composições
                    variadas, que se depositam a partir da suspensão pelo ar, provocando sujeira no ambiente.</p>
            </div>
        </div>
    </div>


    <div class="container p-5 despoeiramento bg-none">
        <div class="mx-5 px-5 mb-5">
            <h2 class="big">O que é despoeiramento?</h2>

            <p><b>O despoeiramento</b> é utilizado para evitar que os materiais particulados em suspensão sejam
                lançados diretamente no meio ambiente. Assim, despoeirar é controlar a emissão de poeira em
                suspensão.</p>

            <p>Os <b>sistemas de despoeiramento</b> são métodos de <b>abatimento de pó</b> eficazes que reduzem os
                custos
                operacionais e diminuem o consumo de água e de energia elétrica.</p>
        </div>

        <div class="p-5 mx-5 bg-white">
            <h2 class="big">Conheça nossas soluções <br> de sistemas de despoeiramento em:</h2>
            <ul class="list">
                <li><a href="/aspersao-em-vias-ou-pista-de-rolamento" target="_self">Estrada de rodagem</a></li>
                <li><a href="/aspersao-em-britagens" target="_self">Unidade de britagem em correias transportadoras</a></li>
                <li><a href="/aspersao-em-patios-de-minerio" target="_self">Pilhas de minério</a></li>
                <li><a href="/lavador-de-rodas-e-chassi" target="_self">Lavador de rodas e de chassi</a></li>
                <li><a href="/aspersao-em-vagoes-de-minerio" target="_self">Vagões de minério</a></li>
            </ul>
        </div>
    </div>



    <div class="despoeiramento bg-green">
        <div class="container p-5">
            <div class="mx-5 px-5">
                <h2 class="big">ÁREAS DE ATUAÇÃO:</h2>
                <ul class="list">
                    <li>Construção civil</li>
                    <li>Indústria</li>
                    <li>Mineração</li>
                    <li>Siderurgia</li>
                </ul>
            </div>
        </div>
    </div>




    <div class="p-5 text-center">
        <a href="contato/" target="_self" class="btn btn-more fs-2">SOLICITE UM CONTATO</a>
    </div>

</main>


<? include '_footer.phtml'; ?>