<?
$title = 'Controlar | Soluções em Despoeiramento e Controle de Poeira';
$description = 'A Controlar oferece soluções em despoeiramento para controle de poeira em setores como mineração e siderurgia, promovendo sustentabilidade e eficiência.';
$keywords = 'soluções em despoeiramento';
include '_header.phtml';
?>

<main role="main">

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">

            <div class="carousel-item active" style="background-image: url('images/vitrine-lavador-rodas-01.jpg')" aria-label="Controlar Sistemas | Lavador de Rodas e Chassis;">
            </div>

            <div class="carousel-item" style="background-image: url('images/vitrine-locacao-equipamentos-estrada-de-rodagem-01.jpg')" aria-label="Controlar Sistemas | Locação de Equipamentos para Aspersão em Vias;">
            </div>

            <!--<div class="carousel-item" style="background-image: url('images/example-image-slide.jpg');">
            </div>-->

        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Anterior</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Próximo</span>
        </a>
    </div>


    <div class="container contato pb-4">
        <h1><strong>Soluções Inovadoras</strong> em Despoeiramento e Controle de Poeira.</h1>

        <form action="#" method="POST">

            <h2>FALE COM UM DE NOSSOS ESPECIALISTAS.</h2>
            <h3><strong>SOLICITE AQUI UM ORÇAMENTO!</strong></h3>

            <input type="text" name="nome" placeholder="Nome Completo *" required>
            <input type="email" name="email" placeholder="E-mail *" required>
            <input type="text" placeholder="Nome da Empresa *" name="empresa" required>
            <input type="tel" placeholder="Telefone com DDD *" name="telefone" required>

            <select id="produto" name="produto">
                <option value="" selected disabled>Qual produto você tem interesse?</option>
                <option value="produto1">Aspersão em Vias de Rolamento</option>
                <option value="produto2">Aspersão em Vagões de Minério</option>
                <option value="produto3">Aspersão em Pátios de Minério</option>
                <option value="produto4">Lavador de Rodas e de Chassi</option>
                <option value="produto5">Aspersão em Britagens</option>
                <option value="produto6">Locação de Equipamentos</option>
            </select>

            <div class="d-flex justify-content-between">
                <p>* Todos os campos são obrigatórios</p>
                <button type="submit">FALE COM O CONSULTOR</button>
            </div>
        </form>


    </div><!-- /.contato -->

    <!-- <div class="especialistas2 p-4 text-center">
            <h4>Somos especialistas <strong>em Despoeiramento.</strong></h4>
        </div> -->

    <div class="only-mobile p-4 text-center bg-white">
        <a href="#" class="btn btn-whatsapp">
            <img src="images/ico-whatsapp.png" alt=""> FALE COM UM ESPECIALISTA
        </a>
    </div>


    <div class="container especialistas py-5 mt-5">

        <div class="row ">
            <div class="col-md-6">
                <h2>
                    Especialistas em Despoeiramento <br>
                    <strong>e Controle de Emissões de Poeira.</strong>

                    <div class="image-box my-3" aria-label="Equipe especializada em despoeiramento desenvolvendo soluções para controle de emissões industriais com foco em sustentabilidade.;"></div>
                </h2>
            </div>
            <div class="col-md-6 d-flex flex-column justify-content-start">

                <p>A crescente preocupação ambiental e o compromisso com a sustentabilidade em todos os setores industriais têm gerado uma demanda cada vez maior por soluções eficazes para controlar as emissões de partículas em suspensão, resultantes dos processos produtivos.</p>

                <p>A CONTROLAR nasceu com o propósito de atender empresas que buscam minimizar essas emissões ao longo de suas cadeias produtivas. Nossa equipe multidisciplinar, formada por gestores experientes e engenheiros altamente qualificados, desenvolve projetos inovadores e totalmente automatizados. Nosso objetivo é oferecer soluções sob medida que garantam excelência, eficiência operacional e valor agregado, atendendo às necessidades específicas de cada cliente.</p>

            </div>
        </div>

    </div><!-- /.especialistas -->

    <div class="equipamentos pt-5">
        <div class="container">

            <h2>
                Nossos <br>
                <strong>Equipamentos e Serviços</strong>
            </h2>

            <p class="feature">Oferecemos manutenção preventiva e corretiva dos nossos projetos.</p>


            <div id="myCarouselEquipamentos" class="carousel slide only-desktop" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#myCarouselEquipamentos" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarouselEquipamentos" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">

                    <!-- INICIO ITEM  -->
                    <div class="carousel-item active">
                        <div class="row">

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-aspersao-em-vagoes-de-minerio.jpg)" aria-label="Despoeiramento - Aspersão em Vagões de Minério | Controle de emissão de material particulado ao longo das ferrovias.;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">EQUIPAMENTO
                                        INOVADOR</div>
                                    <div class="title">ASPERSÃO EM VAGÕES DE MINÉRIO</div>
                                    <p>Reduza as perdas dos materiais finos durante o transporte ferroviário e controla a emissão de material particulado ao longo da ferrovia.</p>
                                    <div class="btn-box">
                                        <a href="/aspersao-em-vagoes-de-minerio/" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-aspersao-em-vias-ou-pista-de-rolamento-asperroad.jpg)" aria-label="Aspersão em vias ou pista de rolamento. Controla a emissão de material particulado em vias ou pistas de rolamento industriais | Asperroad.;">
                                    </div>
                                    <!--<div class="featured"><img src="images/ico-arrow.png" alt="">EQUIPAMENTO
                                        INOVADOR</div>-->
                                    <div class="title">ASPERSÃO EM VIAS OU PISTA DE ROLAMENTO</div>
                                    <p>Aspersão (despoeiramento) em vias ou pista de rolamento (AsperRoad) através do controle da emissão de material particulado.</p>
                                    <div class="btn-box">
                                        <a href="/aspersao-em-vias-ou-pista-de-rolamento/" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-de-grandes-pilhas-de-minerio-aspermovel-para-controle-de-emissoes-fugitivas-de-poeira.jpg)" aria-label="Despoeiramento de grandes pilhas de minério para controle de emissões fugitivas de poeira | Apermóvel;">
                                    </div>
                                    <!--<div class="featured"><img src="images/ico-arrow.png" alt="">Sistema inédito!
                                    </div>-->
                                    <div class="title">DESPOEIRAMENTO DE PILHAS DE MINÉRIOS</div>
                                    <p>Despoeiramento de pilhas de minério para controle de emissões fugitivas de poeira.</p>
                                    <div class="btn-box">
                                        <a href="/despoeiramento-aspersao-sobre-pilha-de-mineirio/" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <!-- FIM ITEM -->

                    <!-- INICIO ITEM  -->
                    <div class="carousel-item">
                        <div class="row">

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/eliminar-poeira-lavador-de-rodas.jpg)" aria-label="Lavador de Rodas - Sistema automático de limpeza que promove a remoção completa de resíduos por meio do jateamento de água | AsperWash;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">SISTEMA INÉDITO!
                                    </div>
                                    <div class="title">LAVADOR DE RODAS E DE CHASSI</div>
                                    <p>Sistema automático de limpeza (AsperWash) que promove a remoção completa de resíduos por meio do jateamento de água.</p>
                                    <div class="btn-box">
                                        <a href="/lavador-de-rodas-e-chassi/" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/aspersao-em-correias-transportadora-de-britagem.jpg)" aria-label="Aspersão em Correias Transportadora de Britagem | Asperbelt;">
                                    </div>

                                    <div class="title">SOLUÇÃO EM ASPERSÃO EM BRITAGEM</div>
                                    <p>Supressão de poeira e abatimento de pó (AsperBelt) em transportadoras de britagem, em correias transportadoras e de transferência.</p>
                                    <div class="btn-box">
                                        <a href="/aspersao-em-britagens/" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>

                            <!--<div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>

                                    <div class="title">Quos sequi voluptatem #2 </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>-->
                        </div>
                    </div>
                    <!-- FIM ITEM -->


                </div>
                <a class="carousel-control-prev" href="#myCarouselEquipamentos" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Anterior</span>
                </a>
                <a class="carousel-control-next" href="#myCarouselEquipamentos" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Próximo</span>
                </a>
            </div>


            <div id="myCarouselEquipamentosMobile" class="carousel slide only-mobile" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="1"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="2"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="3"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="4"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="5"></li>
                </ol>
                <div class="carousel-inner">

                    <div class="carousel-item active">

                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-aspersao-em-vagoes-de-minerio.jpg)" aria-label="Despoeiramento - Aspersão em Vagões de Minério | Controle de emissão de material particulado ao longo das ferrovias.;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">EQUIPAMENTO
                                        INOVADOR</div>
                                    <div class="title">ASPERSÃO EM VAGÕES DE MINÉRIO</div>
                                    <p>Reduza as perdas dos materiais finos durante o transporte ferroviário e controla a emissão de material particulado ao longo da ferrovia.</p>
                                    <div class="btn-box">
                                        <a href="/aspersao-em-vagoes-de-minerio/" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-aspersao-em-vias-ou-pista-de-rolamento-asperroad.jpg)" aria-label="Aspersão em vias ou pista de rolamento. Controla a emissão de material particulado em vias ou pistas de rolamento industriais | Asperroad.;">
                                    </div>

                                    <div class="title">ASPERSÃO EM VIAS OU PISTA DE ROLAMENTO</div>
                                    <p>Aspersão (despoeiramento) em vias ou pista de rolamento (AsperRoad) através do controle da emissão de material particulado.</p>
                                    <div class="btn-box">
                                        <a href="/aspersao-em-vias-ou-pista-de-rolamento/" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="row">
                            <div class="col-md-4">

                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-de-grandes-pilhas-de-minerio-aspermovel-para-controle-de-emissoes-fugitivas-de-poeira.jpg)" aria-label="Despoeiramento de grandes pilhas de minério para controle de emissões fugitivas de poeira | Apermóvel;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">Sistema inédito!
                                    </div>
                                    <div class="title">DESPOEIRAMENTO DE PILHAS DE MINÉRIOS</div>
                                    <p>Sistema automático de limpeza (AsperWash) que promove a remoção completa de resíduos por meio do jateamento de água.</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/eliminar-poeira-lavador-de-rodas.jpg)" aria-label="Lavador de Rodas - Sistema automático de limpeza que promove a remoção completa de resíduos por meio do jateamento de água | AsperWash;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">SISTEMA INÉDITO!</div>
                                    <div class="title">LAVADOR DE RODAS E DE CHASSI</div>
                                    <p>Sistema automático de limpeza (AsperWash) que promove a remoção completa de resíduos por meio do jateamento de água.</p>
                                    <div class="btn-box">
                                        <a href="/lavador-de-rodas-e-chassi/" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/aspersao-em-correias-transportadora-de-britagem.jpg)" aria-label="Aspersão em Correias Transportadora de Britagem | Asperbelt;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">Sistema inédito!
                                    </div>
                                    <div class="title">SOLUÇÃO EM ASPERSÃO EM BRITAGEM</div>
                                    <p>Supressão de poeira e abatimento de pó (AsperBelt) em transportadoras de britagem, em correias transportadoras e de transferência.</p>
                                    <div class="btn-box">
                                        <a href="/aspersao-em-britagens/" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--<div class="carousel-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>

                                    <div class="title">Quos sequi voluptatem #2 </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>-->



                </div>
                <a class="carousel-control-prev" href="#myCarouselEquipamentosMobile" role="button"
                    data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Anterior</span>
                </a>
                <a class="carousel-control-next" href="#myCarouselEquipamentosMobile" role="button"
                    data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Próximo</span>
                </a>
            </div>



        </div>
    </div><!-- /.equipamentos -->

    <div class="bg-white p-4 only-mobile">
        <div class="col-md-12">
            <a href="#" class="text-uppercase btn-more">veja mais produtos</a>
        </div>
    </div>

    <div class="container py-5 text-center clientes">
        <h2>Alguns dos <strong>nossos Clientes</strong></h2>

        <div class="w-100 flex justify-content-center align-items-center">
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-vale.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-anglo.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-csn.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-votorantim.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-inb.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-alcoa.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-avante.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-mrs.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-itaminas.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-groupmoura.png" alt=""></a>
        </div>

    </div><!-- /.clientes -->

</main>

<? include '_footer.phtml'; ?>