<?
$title = 'Soluções em Despoeiramento, Aspersão em Vagões de Minério, Vias e Pista de Rolamento, Abatimento de Pó e Abatimento de Poeira';
$description = 'Coloque a descricao aqui';
$keywords = 'teste1, teste2, teste3';
include '_header.phtml';
?>

<main role="main">

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">

            <div class="carousel-item active" style="background-image: url('images/example-image-slide.jpg');">
            </div>

            <div class="carousel-item" style="background-image: url('images/example-image-slide.jpg');">
            </div>

            <div class="carousel-item" style="background-image: url('images/example-image-slide.jpg');">
            </div>

        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>


    <div class="container contato pb-4">
        <h1><strong>Excelência</strong> no controle de emissões de partículas.</h1>

        <form action="#" method="POST">

            <h2>FALE COM UM DE NOSSOS ESPECIALISTAS.</h2>
            <h3><strong>SOLICITE AQUI UM ORÇAMENTO!</strong></h3>

            <input type="text" name="nome" placeholder="Nome Completo *" required>
            <input type="email" name="email" placeholder="E-mail *" required>
            <input type="text" placeholder="Nome da Empresa *" name="empresa" required>
            <input type="tel" placeholder="Telefone com DDD *" name="telefone" required>

            <select id="produto" name="produto">
                <option value="" selected disabled>Qual produto você tem interesse?</option>
                <option value="produto1">Produto 1</option>
                <option value="produto2">Produto 2</option>
                <option value="produto3">Produto 3</option>
            </select>

            <div class="d-flex justify-content-between">
                <p>* Todos os campos são obrigatórios</p>
                <button type="submit">FALE COM O CONSULTOR</button>
            </div>
        </form>


    </div><!-- /.contato -->

    <!-- <div class="especialistas2 p-4 text-center">
            <h4>Somos especialistas <strong>em Despoeiramento.</strong></h4>
        </div> -->

    <div class="only-mobile p-4 text-center bg-white">
        <a href="#" class="btn btn-whatsapp">
            <img src="images/ico-whatsapp.png" alt=""> FALE COM UM ESPECIALISTA
        </a>
    </div>


    <div class="container especialistas py-5 mt-5">

        <div class="row ">
            <div class="col-md-6">
                <h2>
                    Somos especialistas <br>
                    <strong>em Despoeiramento.</strong>

                    <div class="image-box my-3"></div>
                </h2>
            </div>
            <div class="col-md-6 d-flex flex-column justify-content-start">

                <p>O aumento da preocupação ambiental e o foco na Sustentabilidade em todos os setores da indústria
                    mundial
                    implicam diversas necessidades. Uma das principais é a necessidade de se controlar as emissões
                    de
                    materiais
                    particulados suspensos emitidos pelos processos de produção.</p>

                <p>A CONTROLAR surgiu, então, da necessidade de atender as empresas que desejam controlar estas
                    emissões nas
                    diversas situações existentes na cadeia produtiva. Na CONTROLAR, uma equipe multidisciplinar e
                    altamente
                    qualificada, composta de gestores e de engenheiros de alto nível técnico, é responsável por
                    desenvolver
                    projetos inovadores e completamente automatizados para garantir a excelência e o valor agregado
                    dos
                    projetos elaborados e atender às necessidades específicas de cada cliente.</p>

            </div>
        </div>

    </div><!-- /.especialistas -->

    <div class="equipamentos pt-5">
        <div class="container">

            <h2>
                Nossos <br>
                <strong>Equipamentos e Serviços</strong>
            </h2>

            <p class="feature">Oferecemos manutenção preventiva e corretiva dos nossos projetos.</p>


            <div id="myCarouselEquipamentos" class="carousel slide only-desktop" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#myCarouselEquipamentos" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarouselEquipamentos" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">

                    <div class="carousel-item active">


                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">EQUIPAMENTO
                                        INOVADOR</div>
                                    <div class="title">Quos sequi voluptatem </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>

                                    <div class="title">Quos sequi voluptatem </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">Sistema inédito!
                                    </div>
                                    <div class="title">Quos sequi voluptatem </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>

                    <div class="carousel-item">

                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">EQUIPAMENTO
                                        INOVADOR</div>
                                    <div class="title">Quos sequi voluptatem #2 </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>


                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">Sistema inédito!
                                    </div>
                                    <div class="title">Quos sequi voluptatem #2 </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>


                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>

                                    <div class="title">Quos sequi voluptatem #2 </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>


                        </div>

                    </div>


                </div>
                <a class="carousel-control-prev" href="#myCarouselEquipamentos" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#myCarouselEquipamentos" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>


            <div id="myCarouselEquipamentosMobile" class="carousel slide only-mobile" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="1"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="2"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="3"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="4"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="5"></li>
                </ol>
                <div class="carousel-inner">

                    <div class="carousel-item active">

                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">EQUIPAMENTO
                                        INOVADOR</div>
                                    <div class="title">Quos sequi voluptatem </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>

                                    <div class="title">Quos sequi voluptatem </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="row">
                            <div class="col-md-4">

                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">Sistema inédito!
                                    </div>
                                    <div class="title">Quos sequi voluptatem </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">EQUIPAMENTO
                                        INOVADOR</div>
                                    <div class="title">Quos sequi voluptatem #2 </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">Sistema inédito!
                                    </div>
                                    <div class="title">Quos sequi voluptatem #2 </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>

                                    <div class="title">Quos sequi voluptatem #2 </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>



                </div>
                <a class="carousel-control-prev" href="#myCarouselEquipamentosMobile" role="button"
                    data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#myCarouselEquipamentosMobile" role="button"
                    data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>



        </div>
    </div><!-- /.equipamentos -->

    <div class="bg-white p-4 only-mobile">
        <div class="col-md-12">
            <a href="#" class="text-uppercase btn-more">veja mais produtos</a>
        </div>
    </div>

    <div class="container py-5 text-center clientes">
        <h2>Alguns dos <strong>nossos Clientes</strong></h2>

        <div class="w-100 flex justify-content-center align-items-center">
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-vale.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-anglo.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-csn.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-votorantim.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-inb.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-alcoa.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-avante.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-mrs.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-itaminas.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-groupmoura.png" alt=""></a>
        </div>

    </div><!-- /.clientes -->

</main>

<? include '_footer.phtml'; ?>