<?
$title = 'Lavador de Rodas e de Chassi | Limpeza Eficiente para Veículos';
$description = 'Descubra o Lavador de Rodas e de Chassi da Controlar. Solução eficaz para limpeza de veículos, garantindo eficiência, segurança e sustentabilidade.';
$keywords = 'Lavador de Rodas e de Chassi';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>DESPOEIRAMENTO</b> - LAVADOR DE RODAS E DE CHASSI</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p>Eliminar poeira e outros resíduos inerentes ao transporte terrestre.</p>

                <p>O lavador de chassis desenvolvido pela Controlar é um sistema automático de limpeza que promove a remoção completa de resíduos por meio do jateamento de água. O projeto dos lavadores foi desenvolvido para limpar a parte inferior dos chassis de veículos, e também, os pneus.</p>

                <p>O sistema permite também a lavagem de todo tipo de veículos rodoviários e construído dentro das normas Brasileiras.</p>
                
                <p>Para alcançar tal objetivo, propomos a instalação de um sistema de lavagem que irá distribuir a água através dos bicos aspersores sobre pressão que irão limpar as áreas dos veículos de forma homogênea. Reduzindo/eliminando desta maneira os resíduos neles agregados que poderiam ser transportados e depositados ao longo das vias externas.</p>
            </div>
        </div>
    </div>

    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/eliminar-poeira-lavador-de-rodas.jpg" class="img-responsive mx-" alt="Lavador de rodas e de chassi para limpeza eficiente de veículos industriais e controle de resíduos e de poeira.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMENTO:</h2>
                <p>O sistema é controlado por sensores e é totalmente automatizado. Ele permite que a água circule, de maneira controlada, tanto em circuito fechado quanto em circuito completo.</p>
                
                <p>É um sistema desenvolvido para lavar pneus e a parte inferior de chassis de caminhões e máquinas. O lavador de pneus e chassi já opera em mineradoras, plantas industriais e portos, executando de forma eficiente a eliminação de todo o material impregnado nestes transportes. Todo o processo de lavagem é automático, sendo gerenciado por sensores capazes de controlar a entrada e saída de veículos. Conforme os jatos de água são lançados pelos bicos aspersores, a sujeira escoa pela forma de grelha removendo toda a sujeira impregnada nos pneus e chassi. Sendo assim, os resíduos removidos são depositados no fundo do lavador, sendo transportados diretamente para os tanques(concreto) de decantação e separador de óleo ou direcionado para uma área de rejeito.</p>
            </div>
        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VANTAGENS:</h2>

                <ul class="list">
                    <li>Controle dos impactos ambientais;</li>
                    <li>Baixo custo de operação;</li>
                    <li>Baixo custo de manutenção;</li>
                    <li>Evita o desperdício de água;</li>
                    <li>Remoção completa dos resíduos.</li>
                </ul>

                <br>

                <h2 class="big">APLICAÇÕES:</h2>

                <ul class="list">
                    <li>Acessos de saída de plantas industriais diversas (mineração, cimenteira, siderurgia; etc.);</li>
                    <li>Áreas internas de plantas industriais diversas;</li>
                    <li>Portos.</li>
                </ul>

                <br>
                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="contato/" target="_self" class="btn btn-more fs-2">SOLICITE UM CONTATO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>