<?
$title = 'Locação de Lavadores de Rodas e Chassi e Equipamentos de Batimento de Pó';
$description = 'Alugue lavadores de rodas e chassi e equipamentos de batimento de pó. Soluções completas para controle de poeira e limpeza industrial com eficiência e economia.';
$keywords = 'locação de lavadores de rodas e chassi, locação de equipamentos de batimento de pó';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>LOCAÇÃO DE EQUIPAMENTOS</b> DE BATIMENTO DE PÓ E DE LAVADORES DE RODAS E CHASSI</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p>Na <strong>Controlar Projetos e Engenharia</strong>, a inovação e a eficiência são palavras de ordem. Nós somos a única empresa que comercializa e aluga equipamentos de <strong>batimento de pó em vias de minério e lavadores de rodas e chassi</strong> desenvolvidos por nós mesmos.</p>

                <p>Nossos equipamentos de batimento de pó em vias de minério são os mais avançados do mercado, capazes de reduzir significativamente a emissão de poeira, protegendo a saúde dos trabalhadores e do meio ambiente. Além disso, nossos equipamentos de lavagem de rodas e chassi são extremamente eficazes na limpeza de veículos, reduzindo o tempo de manutenção e aumentando a vida útil dos equipamentos.</p>
                
                <p>Ao escolher a Controlar Projetos e Engenharia, você pode ter certeza de que está escolhendo a qualidade e a eficiência. Nossos equipamentos foram projetados e testados pelos melhores engenheiros do mercado, e nossa equipe de suporte técnico está sempre pronta para ajudá-lo a encontrar a solução perfeita para suas necessidades.</p>
                
                <p>Não perca mais tempo e dinheiro com equipamentos ineficazes. Entre em contato conosco hoje mesmo e descubra como nossos equipamentos de batimento de pó em vias de minério e lavadores de rodas e chassi podem transformar sua operação em uma verdadeira história de sucesso.</p>
                
            </div>
        </div>
    </div>



    <!--<div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/despoeiramento-aspersao-em-vias-ou-pista-de-rolamento-asperroad.jpg" class="img-responsive mx-" alt="Controlar a emissão de material particulado em vias e/ou estradas de rolamento.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMENTO:</h2>
                <p>O sistema de umidificação de vias é composto por um reservatório de água, um conjunto de moto bombas, bicos aspersores e tubulações. Ele é automatizado por meio de uma central eletrônica. Este sistema é muito eficaz porque, já que evita o uso de caminhões pipa, sua utilização reduz o uso de recursos hídricos e de energia elétrica, reduzindo assim os custos operacionais.</p>
            </div>
        </div>
    </div>-->


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VANTAGENS:</h2>

                <ul class="list">
                    <li>As vantagens da locação frente a apção de aquisiçao são que: 1 – Prazo de entrega mas rápido.  2 – Período de contrato a partir de 4 meses,  3 – Manutenções preventivas e corretivas incluidas no valor mensal;</li>
                    <li>Os equipamentos se destinam principalmente para mineradoras e siderurgicas;</li>
                    <li>Lavadores de alta eficiência e com grande economia de água chegando a recuperar 90% da média utilizada em outras soluções de mercado;</li>
                    <li>De fácil operação e manutenção;</li>
                    <li>Lavadores com garantia de 5 anos.</li>
                </ul>

                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="contato/" target="_self" class="btn btn-more fs-2">SOLICITE UM CONTATO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>