<?
$title = 'Projetos Executados de Despoeiramento | Exemplos de Sucesso da Controlar';
$description = 'Explore os projetos executados de despoeiramento da Controlar. Veja vídeos com soluções eficazes para controle de poeira.';
$keywords = 'projetos executados de despoeiramento';
include '_header.phtml';
?>


<main role="main" class="internal">


    <div class="breadcrumb container">
        <h1><b>PROJETOS EXECUTADOS</b></h1>
    </div>

    <div class="bg-white">

        <div class="container projetos">

            <h3 class="text-center py-5">Conheça alguns executados pela Controlar</h3>


            <!-- Item -->
            <div class="bg-silver"></div>
            <div class="z-100">

                <div class="px-5">
                    <h2 class="pt-4 pb-3 px-5">Aspermóvel | Solução Móvel para Controle de Poeira</h2>
                    <!--<p class="px-5">Conheça o Aspermóvel, uma solução móvel e inovadora para aspersão e controle de poeira. Ideal para pátios, vias de rolamento e ambientes que exigem flexibilidade operacional.</p>-->
                </div>

                <div class="youtube-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/wxgaUP--lW8?si=hpjcqhEcNeGOXL_H"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>


            <!-- Item -->
            <div class="bg-silver"></div>
            <div class="z-100">

                <div class="px-5">
                    <h2 class="pt-4 pb-3 px-5">AsperWagon | Aspersão em Vagões de Minério</h2>
                    <!--<p class="px-5">Veja o AsperWagon em ação, garantindo o controle eficiente de poeira em vagões de minério, com tecnologias avançadas e resultados sustentáveis.</p>-->
                </div>


                <div class="youtube-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/eMxKUJNbshI?si=qiRYio4Iz3HJlVez"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>


        </div>


        <div class="pb-5 text-center">
            <a href="contato/" target="_self" class="btn btn-more fs-2 w-400">DÚVIDAS? SOLICITE UM CONTATO</a>
        </div>

    </div>

</main>


<? include '_footer.phtml'; ?>