<?
$title = 'Soluções em Despoeiramento, Aspersão em Vagões de Minério, Vias e Pista de Rolamento, Abatimento de Pó e Abatimento de Poeira';
$description = 'Coloque a descricao aqui';
$keywords = 'teste1, teste2, teste3';
include '_header.phtml';
?>


<main role="main" class="internal">


    <div class="breadcrumb container">
        <b>PROJETOS INOVADORES</b>
    </div>

    <div class="bg-white">

        <div class="container projetos">

            <h3 class="text-center py-5">Conheça alguns de nossos projetos inovadores</h3>


            <!-- Item -->
            <div class="bg-silver"></div>
            <div class="z-100">

                <h2 class="pt-4 pb-3 px-5">AsperMóvel</h2>

                <div class="youtube-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/2tMY9oX7T1Q?si=IOgRkqdtZr4UUd9_"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>

            <!-- Item -->
            <div class="bg-silver"></div>
            <div class="z-100">

                <h2 class="pl pt-4 pb-3">AsperWash - Lavador de Rodas e de Chassi</h2>

                <div class="youtube-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>

        </div>


        <div class="pb-5 text-center">
            <a href=" #" class="btn btn-more fs-2 w-400">DÚVIDAS? SOLICITE UM CONTATO</a>
        </div>

    </div>

</main>


<? include '_footer.phtml'; ?>