<?
$title = 'Projetos Inovadores de Despoeiramento | Soluções Personalizadas Controlar';
$description = 'Explore projetos inovadores de despoeiramento desenvolvidos pela Controlar. Descubra soluções personalizadas e eficientes para controle de poeira industrial.';
$keywords = 'projetos inovadores de despoeiramento';
include '_header.phtml';
?>


<main role="main" class="internal">


    <div class="breadcrumb container">
        <h1><b>PROJETOS INOVADORES</b></h1>
    </div>

    <div class="bg-white">

        <div class="container projetos">

            <h3 class="text-center py-5">Conheça alguns de nossos projetos inovadores</h3>


            <!-- Item -->
            <div class="bg-silver"></div>
            <div class="z-100">

                <div class="px-5">
                    <h2 class="pt-4 pb-3 px-5">Aspermóvel | Solução Móvel para Controle de Poeira</h2>
                    <p class="px-5">Conheça o Aspermóvel, uma solução móvel e inovadora para aspersão e controle de poeira. Ideal para pátios, vias de rolamento e ambientes que exigem flexibilidade operacional.</p>
                </div>

                <div class="youtube-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/2tMY9oX7T1Q?si=IOgRkqdtZr4UUd9_"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>


            <!-- Item -->
            <div class="bg-silver"></div>
            <div class="z-100">

                <div class="px-5">
                    <h2 class="pt-4 pb-3 px-5">AsperWagon | Aspersão em Vagões de Minério</h2>
                    <p class="px-5">Veja o AsperWagon em ação, garantindo o controle eficiente de poeira em vagões de minério, com tecnologias avançadas e resultados sustentáveis.</p>
                </div>


                <div class="youtube-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/Bwacn0D1x2M?feature=oembed"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>


            <!-- Item -->
            <div class="bg-silver"></div>
            <div class="z-100">

                <div class="px-5">
                    <h2 class="pt-4 pb-3 px-5">AsperWash | Sistema Inovador de Lavagem de Rodas e Chassi</h2>
                    <p class="px-5">Descubra o AsperWash, solução eficiente para lavagem de rodas e chassi em ambientes industriais. Reduza resíduos e garanta limpeza com sustentabilidade e alta performance.</p>
                </div>


                <div class="youtube-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>

        </div>


        <div class="pb-5 text-center">
            <a href="contato/" target="_self" class="btn btn-more fs-2 w-400">DÚVIDAS? SOLICITE UM CONTATO</a>
        </div>

    </div>

</main>


<? include '_footer.phtml'; ?>