<?
$title = 'Soluções em Despoeiramento, Aspersão em Vagões de Minério, Vias e Pista de Rolamento, Abatimento de Pó e Abatimento de Poeira';
$description = 'Coloque a descricao aqui';
$keywords = 'teste1, teste2, teste3';
include '_header.phtml';
?>

<main role="main" class="internal">


    <div class="breadcrumb container">
        <b>Quem somos</b>
    </div>

    <div class="bg-white quem-somos">

        <div class="container py-5">

            <div class="row">
                <div class="col-md-6">
                    <h2><strong>Somos especialistas</strong> <br>
                        em Despoeiramento.</h2>

                    <img src="images/example-image.jpg" class="img-responsive mt-1" alt="">
                </div>
                <div class="col-md-6 d-flex flex-column justify-content-end">
                    <p>O aumento da preocupação ambiental e o foco na Sustentabilidade em todos os setores da
                        indústria mundial implicam diversas necessidades. Uma das principais é a necessidade de se
                        controlar as emissões de materiais particulados suspensos emitidos pelos processos de
                        produção.</p>

                    <p>A CONTROLAR surgiu, então, da necessidade de atender as empresas que desejam controlar estas
                        emissões nas diversas situações existentes na cadeia produtiva. Na CONTROLAR, uma equipe
                        multidisciplinar e altamente qualificada, composta de gestores e de engenheiros de alto
                        nível técnico, é responsável por desenvolver projetos inovadores e completamente
                        automatizados para garantir a excelência e o valor agregado dos projetos elaborados e
                        atender às necessidades específicas de cada cliente.</p>
                </div>
            </div>


        </div><!-- /.quem somos -->


    </div>

    <div class="bg-green quem-somos py-5">

        <div class="container">

            <h3>NOSSA MISSÃO</h3>
            <p>Desenvolver projetos inovadores de sistemas de abatimento de pó, por meio da alta tecnologia, para
                promover o bem-estar e a sustentabilidade.</p>

            <h3>NOSSA VISÃO</h3>
            <p>Alcançar a admiração e o respeito dos clientes por meio da aplicabilidade, da confiabilidade e da
                praticidade dos projetos desenvolvidos.</p>

            <h3>NOSSOS VALORES</h3>

            <ul>
                <li><strong>INOVAÇÃO:</strong> Oferecer para o mercado produtos excepcionais, desenvolvidos por meio
                    de
                    alta tecnologia, para atender às necessidades individuais de cada cliente.</li>
                <li><strong>SUSTENTABILIDADE:</strong> Apresentar para o mercado soluções com baixos custos
                    operacionais
                    que promovam, principalmente, economia de energia elétrica e o reuso de água.</li>
                <li><strong>COMPROMETIMENTO:</strong> Entregar todos os projetos respeitando as normas vigentes e os
                    prazos estabelecidos.</li>
                <li><strong>ÉTICA:</strong> Respeitar os colaboradores, os clientes e os fornecedores para
                    consolidar boas e transparentes relações.</li>
            </ul>


        </div>

    </div>


    <div class="p-5 text-center">
        <a href=" #" class="btn btn-more fs-2">SOLICITE UM CONTATO</a>
    </div>

</main>


<? include '_footer.phtml'; ?>