<!-- FOOTER -->

<footer class="pt-4 pb-0">

    <div class="text-center brand">
        <a href="./">
            <img src="images/controlar-logo-black.png" alt="">
        </a>
    </div>

    <div class="only-mobile container text-white text-center">

        <h3 class="">A través de la tecnología, buscamos ofrecer a nuestros clientes soluciones innovadoras para reducir los impactos ambientales y promover la sostenibilidad.</h4>

            <a href="#" class="btn btn-whatsapp my-4">
                <img src="images/ico-whatsapp.png" alt=""> HABLE CON UN ESPECIALISTA
            </a>

            <a href="#" target="_blank" class="btn btn-youtube my-4">
                <img src="images/ico-youtube-white.png" alt="">
            </a><br>
    </div>

    <div class="menu container d-flex justify-content-between">

        <!-- Links principais -->
        <section>
            <ul style=" list-style-type: none; padding: 0;">
                <li><a href="es/supresion-de-polvo/" target="_self">¿Qué es la Supresión de Polvo?</a></li>
                <li><a href="es/nuestros-clientes-y-socios/" target="_self">Clientes y Socioss</a></li>
                <li><a href="es/quienes-somos/" target="_self">Quiénes Somos</a></li>
                <li><a href="es/contacto/" target="_self">Contacto</a>
                </li>
            </ul>
        </section>

        <!-- Serviços de aspersão -->
        <section>
            <ul style="list-style-type: none; padding: 0;">
                <li><a href="es/aspersion-en-trituradoras/" target="_self">Aspersión en Trituradoras</a></li>
                <li><a href="es/aspersion-en-cajas-de-camiones/" target="_self">Aspersión en Cajas de Camiones</a></li>
                <li><a href="es/aspersion-en-patios-de-mineral/" target="_self">Aspersión en Patios de Mineral</a></li>
                 <li><a href="es/aspersion-en-vagones-de-mineral/" target="_self">Aspersión en Vagones de Mineral</a></li>
                <li><a href="es/aspersion-en-vias-de-rodamiento/" target="_self">Aspersión en Vías de Rodamiento</a></li>
                <li><a href="es/lavador-de-ruedas-y-chasis/" target="_self">Lavador de Ruedas y Chasis</a></li>
                <li><a href="es/alquiler-de-equipos-de-supresion-de-polvo-y-lavadores-de-ruedas-y-chasis/" target="_self">Alquiler de Equipos</a></li>
            </ul>
        </section>

        <section class="social">
            SÍGUENOS EN NUESTRAS<br> REDES SOCIALES<br>
            <a href="https://www.youtube.com/@controlarsistemas3442" target="_blank"><img src="images/ico-youtube.png" class="zoom" alt=""></a>
        </section>


    </div>
    <div class="sign">
        <div class="container">
            <a href="https://agenciadecriacao.com.br" target="_blank">
                <img src="images/agencia-criacao.png" alt="">
            </a>
        </div>
    </div>

</footer><!-- /.FOOTER -->


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script>
    window.jQuery || document.write('<script src="/assets/js/vendor/jquery-slim.min.js"><\/script>')
</script>
<script src="/dist/js/bootstrap.bundle.min.js?v=2"
    integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o"
    crossorigin="anonymous"></script>

</body>

</html>