<!doctype html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="<?= $description; ?>">
    <meta name="keywords" content="<?= $keywords; ?>">

    <meta name="author" content="Agência de Criação & Brainatwork TI">


    <?php
    $currentUrl = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://" . $_SERVER['HTTP_HOST'];
    echo '<base href="' . $currentUrl . '" target="_blank">';
    ?>

    <title><?= $title; ?></title>


    <!-- Bootstrap core CSS -->
    <link href="/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
        rel="stylesheet">

    <link href="css/main.css?v4=true<?= date("Hisdmy"); ?>" rel="stylesheet">

    <!-- Favicon -->
    <link rel="icon" href="images/favicon-32x32.png" sizes="32x32" />

</head>

<body>
    <header>



        <nav class="navbar navbar-expand-md container p-0">

            <div class="dd-flex w-100">
                <div>
                    <a class="navbar-brand " href="./es/" target="_self">
                        <img src="images/controlar-logo.png" class="only-desktop" alt="Logotipo de Controlar Sistemas, especialistas en soluciones de supresión de polvo y control de emisiones de partículas.">
                        <img src="images/controlar-logo-mobile.png" class="only-mobile" alt="Logotipo de Controlar Sistemas, especialistas en soluciones de supresión de polvo y control de emisiones de partículas.">
                    </a>
                </div>

                <div class="flex-grow-1 d-flex flex-column justify-content-between">

                    <div class="social-links w-100 d-flex justify-content-between align-items-center">

                        <a href="mailto: comercial@controlarsistemas.com" class="zoom"> <img src="images/ico-emaill.png" alt="">
                            comercial@controlarsistemas.com
                        </a>
                        <a href="#" class="zoom"> <img src="images/ico-time.png" alt="">
                            De lun. a vie., de 8 a 18 h.
                        </a>
                        <a href="https://www.youtube.com/@controlarsistemas3442" class="zoom" target="_blank"> <img src="images/ico-youtube.png" alt="">
                            Visita nuestro YouTube
                        </a>

                        <div class="flags">
                            <a href="./" target="_self"><img class="zoom" src="images/flag-brasil.png" alt=""></a><a href="./en/" target="_self"><img class="zoom"
                                    src="images/flag-eua.png" alt=""></a><a href="./es/" target="_self"><img class="zoom" src="images/flag-spain.png"
                                    alt=""></a>
                        </div>
                    </div>


                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <div class="line"></div>
                        <div class="line"></div>
                        <div class="line"></div>
                    </button>


                    <div class="collapse navbar-collapse align-items-end justify-content-between flex-grow-1"
                        id="navbarCollapse">
                        <ul class="navbar-nav justify-content-between d-flex flex-grow-1">

                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link menu-item dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">Soluciones</a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="es/aspersion-en-trituradoras/" target="_self">ASPERSIÓN EN TRITURADORAS</a>
                                    <a class="dropdown-item" href="es/aspersion-en-cajas-de-camiones/" target="_self">ASPERSIÓN EN CAJAS DE CAMIONES</a>
                                    <a class="dropdown-item" href="es/aspersion-en-patios-de-mineral/" target="_self">ASPERSIÓN EN PATIOS DE MINERAL</a>
                                    <a class="dropdown-item" href="es/aspersion-en-vagones-de-mineral/" target="_self">ASPERSIÓN EN VAGONES DE MINERAL</a>
                                    <a class="dropdown-item" href="es/aspersion-en-vias-de-rodamiento/" target="_self">ASPERSIÓN EN VÍAS DE RODAMIENTO</a>
                                    <a class="dropdown-item" href="es/lavador-de-ruedas-y-chasis/" target="_self">LAVADOR DE RUEDAS Y CHASIS</a>
                                    <a class="dropdown-item" href="es/alquiler-de-equipos-de-supresion-de-polvo-y-lavadores-de-ruedas-y-chasis/" target="_self">ALQUILER DE EQUIPOS</a>
                                </div>
                            </li>


                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link menu-item dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">Proyectos</a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> <a
                                        class="dropdown-item" href="es/proyectos-innovadores/" target="_self">PROYECTOS INNOVADORES</a>
                                    <a class="dropdown-item" href="es/proyectos-ejecutados/" target="_self">PROYECTOS EJECUTADOS</a>
                                </div>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="es/supresion-de-polvo/" target="_self">Supresión de Polvo</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="es/nuestros-clientes-y-socios/" target="_self">Clientes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="es/quienes-somos/" target="_self">Quiénes Somos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="es/contacto/" target="_self">Contacto</a>
                            </li>


                        </ul>
                    </div>

                </div>

            </div>




        </nav>
    </header>


    <!-- HEADER end -->