<?
$title = 'Alquiler de Lavadoras de Ruedas y Chasis y Equipos de Supresión de Polvo';
$description = 'Alquile lavadoras de ruedas y chasis y equipos de supresión de polvo. Soluciones completas para el control de polvo y la limpieza industrial con eficiencia y ahorro.';
$keywords = 'alquiler de lavadoras de ruedas y chasis, alquiler de equipos de supresión de polvo';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>ALQUILER DE EQUIPOS</b> DE SUPRESIÓN DE POLVO Y LAVADORAS DE RUEDAS Y CHASIS</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p>En <strong>Controlar Proyectos e Ingeniería</strong>, la innovación y la eficiencia son nuestra prioridad. Somos la única empresa que comercializa y alquila equipos de supresión de polvo en vías de mineral y lavadoras de ruedas y chasis desarrolladas internamente.</p>

                <p>Nuestros equipos de supresión de polvo para vías de mineral son los más avanzados del mercado, capaces de reducir significativamente las emisiones de polvo, protegiendo la salud de los trabajadores y el medio ambiente. Además, nuestras lavadoras de ruedas y chasis son extremadamente eficaces en la limpieza de vehículos, reduciendo el tiempo de mantenimiento y prolongando la vida útil de los equipos.</p>
                
                <p>Al elegir Controlar Proyectos e Ingeniería, puede estar seguro de que está eligiendo calidad y eficiencia. Nuestros equipos han sido diseñados y probados por los mejores ingenieros del mercado, y nuestro equipo de soporte técnico está siempre listo para ayudarlo a encontrar la solución perfecta para sus necesidades.</p>
                
                <p>No pierda más tiempo y dinero con equipos ineficaces. Póngase en contacto con nosotros hoy mismo y descubra cómo nuestros equipos de supresión de polvo en vías de mineral y lavadoras de ruedas y chasis pueden transformar su operación en una verdadera historia de éxito.</p>
                
            </div>
        </div>
    </div>



    <!--<div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/despoeiramento-aspersao-em-vias-ou-pista-de-rolamento-asperroad.jpg" class="img-responsive mx-" alt="Controlar a emissão de material particulado em vias e/ou estradas de rolamento.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMENTO:</h2>
                <p>O sistema de umidificação de vias é composto por um reservatório de água, um conjunto de moto bombas, bicos aspersores e tubulações. Ele é automatizado por meio de uma central eletrônica. Este sistema é muito eficaz porque, já que evita o uso de caminhões pipa, sua utilização reduz o uso de recursos hídricos e de energia elétrica, reduzindo assim os custos operacionais.</p>
            </div>
        </div>
    </div>-->


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VENTAJAS:</h2>

                <ul class="list">
                    <li>Entrega más rápida en comparación con la compra;</li>
                    <li>Contratos a partir de 4 meses;</li>
                    <li>Mantenimiento preventivo y correctivo incluido en el valor mensual;</li>
                    <li>Equipos destinados principalmente a empresas mineras y siderúrgicas;</li>
                    <li>Lavadoras de alta eficiencia con un gran ahorro de agua, recuperando hasta el 90% del consumo promedio de otras soluciones del mercado;</li>
                    <li>Fácil operación y mantenimiento;</li>
                    <li>Lavadoras con garantía de 5 años.</li>
                </ul>

                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="/es/contacto/" target="_self" class="btn btn-more fs-2">SOLICITE UN CONTACTO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>