<?
$title = 'Aspersor de Agua y Polímero para Cajas de Camiones | Control Eficiente de Polvo';
$description = 'El Aspersor de Agua y Polímero para Cajas de Camiones reduce la dispersión de polvo sin necesidad de lona. Una solución sostenible y eficiente para el control ambiental.';
$keywords = 'Aspersor de Agua y Polímero';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>SUPRESIÓN DE POLVO</b> - ASPERSOR DE AGUA Y POLÍMERO PARA CAJAS DE CAMIONES</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p>El Semipórtico es un sistema diseñado para inyectar agua y polímero, formando una solución protectora en las superficies de las cargas en camiones, eliminando la necesidad de lonas y evitando la propagación de polvo al medio ambiente.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/aspersor-de-agua-e-polimero-para-cacamba-de-caminhoes.jpg" class="img-responsive mx-" alt="Aspersor de água e polímero para caçamba de caminhões, solução para controle de poeira sem uso de lona.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMIENTO:</h2>
                <p>El sistema puede operar de manera conjunta y simultánea con el lavador.</p>
            </div>

            <!--<div class="image text-center mx-5 px-5">
                <img src="images/planta-projeto-despoeiramento-aspersao-em-vagoes-de-minerio.jpg" class="img-responsive mx-" alt="Despoeiramento - Aspersão em Vagões de Minério | Projeto para controle de poeira emitidos por vagões de minério.">
            </div>-->

        </div>
    </div>


    <!--<div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VANTAGENS:</h2>

                <ul class="list">
                    <li>Controle dos impactos ambientais;</li>
                    <li>Redução da perda de carga;</li>
                    <li>Baixo custo de operação;</li>
                    <li>Baixo custo de manutenção;</li>
                    <li>Evita o desperdício de água;</li>
                    <li>Remoção completa dos resíduos.</li>
                </ul>

                <br>

            </div>

            <div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/eMxKUJNbshI?si=TGmAqaoLDYXAFIAR"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>
        </div>
    </div>-->




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="/es/contacto/" target="_self" class="btn btn-more fs-2">SOLICITE UN CONTACTO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>