<?
$title = 'Aspersión en Trituración | Control de Polvo con Eficiencia - AsperBelt';
$description = 'Conozca AsperBelt, la solución especializada en aspersión en trituración. Reduzca el polvo en el proceso industrial, promoviendo la eficiencia y la sostenibilidad.';
$keywords = 'Aspersión en Trituración';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1>
            <b>SUPRESIÓN DE POLVO</b> - ASPERSIÓN EN TRITURACIÓN | ASPERBELT
        </h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p><strong>Supresión de polvo y control de partículas</strong> en transportadores de trituración, cintas transportadoras y puntos de transferencia, entre otros procesos.</p>

                <p>El <strong>sistema de aspersión</strong> en vías y/o pistas de rodamiento desarrollado por Controlar es un sistema automático que controla la emisión de material particulado en entornos industriales.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/aspersao-em-correias-transportadora-de-britagem.jpg" class="img-responsive mx-" alt="Sistema AsperBelt de aspersão em britagem para controle eficaz de poeira no ambiente industrial.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMIENTO:</h2>
                <p>El sistema promueve la aspersión de agua mediante motobombas sin necesidad de compresores. El agua se almacena en un depósito y el sistema se controla mediante sensores y activaciones automáticas, según la programación deseada por el cliente. Este sistema no utiliza detergentes, tensioactivos ni otros productos químicos.</p>
            </div>
        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VENTAJAS:</h2>

                <ul class="list">
                    <li>Control de los impactos ambientales;</li>
                    <li>Control de la emisión de polvo;</li>
                    <li>Bajo costo de operación;</li>
                    <li>Bajo costo de mantenimiento;</li>
                    <li>Evita el desperdicio de agua;</li>
                    <li>Eliminación completa de residuos;</li>
                    <li>No satura el material.</li>
                </ul>

                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="/es/contacto/" target="_self" class="btn btn-more fs-2">SOLICITE UN CONTACTO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>