<?
$title = 'Aspersión en Patio de Mineral | Control de Polvo con Alta Eficiencia';
$description = 'Garantice un ambiente más limpio y sostenible con nuestra solución de aspersión en patios de mineral. Control eficaz de polvo para una máxima eficiencia operativa.';
$keywords = 'Aspersión en Patio de Mineral';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1>
            <b>SUPRESIÓN DE POLVO</b> - ASPERSIÓN EN PATIO DE MINERAL
        </h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p>Supresión de polvo en grandes pilas de mineral para el control de emisiones fugitivas de polvo.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/despoeiramento-de-grandes-pilhas-de-minerio-aspermovel-para-controle-de-emissoes-fugitivas-de-poeira.jpg" class="img-responsive mx-" alt="Sistema de aspersión en patio de mineral para el control de polvo y la sostenibilidad industrial.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMIENTO:</h2>
                <p>Este sistema permite paradas y reversiones, ahorra energía y es ideal para la reducción del impacto ambiental, eliminando la necesidad de camiones cisterna y ahorrando una gran cantidad de agua.</p>
            </div>
        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VENTAJAS:</h2>

                <ul class="list">
                    <li>Tubería de acero al carbono;</li>
                    <li>Permite la aplicación de polímeros;</li>
                    <li>Sistema de automatización inteligente mediante PLC.</li>
                </ul>

                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="/es/contacto/" target="_self" class="btn btn-more fs-2">SOLICITE UN CONTACTO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>