<?
$title = 'Aspersión en Vagones de Mineral | Control de Polvo con AsperWagon';
$description = 'Descubra AsperWagon, la solución líder en aspersión en vagones de mineral. Controle las emisiones de polvo, aumente la eficiencia operativa y promueva la sostenibilidad industrial.';
$keywords = 'Aspersión en Vagones de Mineral';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>SUPRESIÓN DE POLVO</b> - ASPERSIÓN EN VAGONES DE MINERAL | ASPERWAGON</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p>Reducir la pérdida de materiales finos durante el transporte ferroviario y controlar la emisión de material particulado a lo largo de la vía férrea.</p>

                <p>El sistema de aspersión de agua en vagones desarrollado por Controlar es un sistema automático de rociado de agua y polímero que promueve la reducción de la pérdida de materiales finos durante el transporte ferroviario y el control de las emisiones de material particulado a lo largo de la vía férrea.</p>
                
                <p>Para la planta, desarrollamos un sistema de aspersión con aplicación de polímeros, con bloqueo entre vagones e interrupción del flujo para evitar que la solución caiga al suelo entre los intervalos de los vagones o sobre las locomotoras.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/despoeiramento-aspersao-em-vagoes-de-minerio.jpg" class="img-responsive mx-" alt="Sistema AsperWagon de aspersão em vagões de minério para controle eficaz de poeira industrial.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMIENTO:</h2>
                <p>El sistema es controlado por sensores y totalmente automatizado. Controla la aspersión de agua sobre los materiales transportados por los vagones. A través del control del tiempo y del flujo de aspersión, puede operar a diferentes velocidades de composición.</p>
                
                <p>Controlar proporciona toda la ingeniería necesaria para el desarrollo, fabricación y suministro de los equipos.</p>
                
                <p>Los sensores se instalan para la detección de obstáculos en la vía, manteniendo diferentes alturas para identificar la presencia de locomotoras o vagones. También detectan el intervalo entre vagones. La lectura de obstáculos, ya sea un vagón por su menor altura o una locomotora por su mayor altura, activa una señal enviada al PLC.</p>
            </div>

            <div class="image text-center mx-5 px-5">
                <img src="images/planta-projeto-despoeiramento-aspersao-em-vagoes-de-minerio.jpg" class="img-responsive mx-" alt="Supresión de Polvo - Aspersión en Vagones de Mineral | Proyecto para el control de polvo emitido por vagones de mineral.">
            </div>

        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VENTAJAS:</h2>

                <ul class="list">
                    <li>Control de impactos ambientales;</li>
                    <li>Reducción de la pérdida de carga;</li>
                    <li>Bajo costo de operación;</li>
                    <li>Bajo costo de mantenimiento;</li>
                    <li>Evita el desperdicio de agua;</li>
                    <li>Eliminación completa de residuos.</li>
                </ul>

                <br>

            </div>

            <div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/eMxKUJNbshI?si=TGmAqaoLDYXAFIAR"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="/es/contacto/" target="_self" class="btn btn-more fs-2">SOLICITE UN CONTACTO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>