<?
$title = 'Aspersión en Vías de Rodamiento | Control de Polvo con Eficiencia - AsperRoad';
$description = 'Descubra AsperRoad, una solución innovadora para la aspersión en vías de rodamiento. Reduzca las emisiones de polvo, garantice la sostenibilidad y la eficiencia operativa en su industria.';
$keywords = 'Aspersión en Vías de Rodamiento';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>SUPRESIÓN DE POLVO</b> - ASPERSIÓN EN VÍAS O PISTAS DE RODAMIENTO | ASPERROAD</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p>Controlar la emisión de material particulado en vías y/o caminos de rodamiento.</p>

                <p>El sistema de aspersión en vías y/o pistas de rodamiento desarrollado por Controlar es un sistema automático que gestiona la emisión de material particulado en entornos industriales.</p>
                
                <p>Esta solución se enfoca en la reducción de costos de inversión, mantenimiento y operación, manteniendo la misma calidad y efectividad técnica para la contención de partículas en suspensión.</p>
                
                <p>Este sistema elimina la necesidad de camiones cisterna para la humectación de las vías, siendo una propuesta automatizada notoriamente eficaz y eficiente.</p>
            </div>
        </div>
    </div>



    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/despoeiramento-aspersao-em-vias-ou-pista-de-rolamento-asperroad.jpg" class="img-responsive mx-" alt="Control de la emisión de material particulado en vías y/o caminos de rodamiento.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMIENTO:</h2>
                <p>El sistema de humidificación de vías está compuesto por un depósito de agua, un conjunto de motobombas, boquillas aspersoras y tuberías. Está automatizado mediante una central electrónica. Este sistema es altamente eficiente, ya que al eliminar el uso de camiones cisterna, reduce el consumo de recursos hídricos y de energía eléctrica, disminuyendo así los costos operativos.</p>
                
                <p>Los aspersores cuentan con control y activación independiente, permitiendo que cada sector reciba una programación específica. Actualmente, son los aspersores más utilizados en sistemas de alta precisión. Garantizan que el caudal del sistema se ajuste siempre a la condición más eficaz y equilibrada.</p>
                
                <p>Este sistema permite la activación en múltiples puntos, adoptando el principio de manejo eficiente del caudal y ofreciendo gran flexibilidad para atender necesidades específicas</p>
            </div>
        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VENTAJAS:</h2>

                <ul class="list">
                    <li>Control de impactos ambientales;</li>
                    <li>Bajo costo de operación;</li>
                    <li>Bajo costo de mantenimiento;</li>
                    <li>Evita el desperdicio de agua;</li>
                    <li>Control completo de la emisión de material particulado durante el transporte interno.</li>
                </ul>

                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="/es/contacto/" target="_self" class="btn btn-more fs-2">SOLICITE UN CONTACTO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>