<?
$title = 'Contáctenos | Solución para el Control de Emisión de Polvo';
$description = 'Hable con Controlar y descubra la solución ideal para el control de emisión de polvo en su industria. Soporte especializado y atención personalizada.';
$keywords = 'solución para el control de emisión de polvo';
include '_header.phtml';
?>

<main role="main" class="internal">


    <div class="breadcrumb container">
        <h1><b>Contacto</b></h1>
    </div>

    <div class="relative h-10">
        <div class="bg-white max-height-500"></div>
    </div>

    <div class="container contato px-5 pb-5">

        <div class="box">
            <h1 class="px-3"><strong>¡Tenemos la mejor solución</strong> para el control de emisión de polvo!</h1>


            <form id="meuFormulario" action="_mailSender.php" method="POST">

                <h2>¡SOLICITE AQUÍ UN CONTACTO COMERCIAL</h2>
                <h3><strong>CON UNO DE NUESTROS ESPECIALISTAS!</strong></h3>

                <input type="text" name="nome" placeholder="Nombre Completo *" required>
                <input type="email" name="email" placeholder="Correo Electrónico *" required>
                <input type="text" placeholder="Nombre de la Empresa *" name="empresa" required>
                <input type="tel" placeholder="Teléfono con Código de Área *" name="telefone" required>

                <select id="produto" name="produto">
                    <option value="" selected disabled>¿En qué producto está interesado?</option>
                    <option value="Aspersión en Cajas de Camiones">Aspersión en Cajas de Camiones</option>
                    <option value="Aspersión en Vías de Rodamiento">Aspersión en Vías de Rodamiento</option>
                    <option value="Aspersión en Vagones de Mineral">Aspersión en Vagones de Mineral</option>
                    <option value="Aspersión en Patios de Mineral">Aspersión en Patios de Mineral</option>
                    <option value="Lavador de Ruedas y Chasis">Lavador de Ruedas y Chasis</option>
                    <option value="Aspersión en Trituradoras">Aspersión en Trituradoras</option>
                    <option value="Alquiler de Equipos">Alquiler de Equipos</option>
                </select>

                <select id="como_conheceucomo_conheceu" name="como_conheceu">
                    <option value="" selected disabled>¿Cómo conoció a Controlar?</option>
                    <option value="Buscando en Google">Buscando en Google</option>
                    <option value="En LinkedIn">En LinkedIn</option>
                    <option value="En Instagram">En Instagram</option>
                    <option value="En YouTube">En YouTube</option>
                    <option value="En Eventos Comerciales">En Eventos Comerciales</option>
                    <option value="Recomendación de Terceros">Recomendación de Terceros</option>
                </select>

                <textarea name="texto"
                    placeholder="Describa aquí su proyecto, los problemas que ha experimentado y sus necesidades. Nos pondremos en contacto con usted lo antes posible."
                    id=""></textarea>

                <div id="mensagemFeedback"></div>

                <input type="hidden" name="type" value="orcamento" />
                <input type="hidden" id="recaptchaToken" name="recaptchaToken" value="" />


                <div class="d-flex justify-content-between">
                    <p>* Todos los campos son obligatorios</p>
                    <button type="submit" id="meuBotao">HABLE CON EL CONSULTOR</button>
                </div>
            </form>

        </div>


    </div><!-- /.contato -->


</main>


<? include '_footer.phtml'; ?>