<div class="dt-cookie-consent dt-cookiemessage-bottom">
    <div class="container">
        <p class="dt_cookie_text">
            Utilizamos cookies para oferecer melhor experiência, melhorar o desempenho, analisar como você interage em nosso site e personalizar conteúdo. Ao utilizar este site, você concorda com o uso de cookies.
        </p>

        <div class="d-flex text-center">
            <a href="#" class="btn btn-more dt-sc-button filled small dt-cookie-consent-button accept-cookies">Aceitar</a>
            <a href="#" class="btn btn-more dt-sc-button filled small dt-cookie-consent-button reject-cookies">Recusar</a>
        </div>
    </div>
</div>