<?
$title = 'Controlar | Soluciones en Supresión de Polvo y Control de Emisiones';
$description = 'Controlar ofrece soluciones en supresión de polvo para el control de emisiones en sectores como la minería y la siderurgia, promoviendo sostenibilidad y eficiencia.';
$keywords = 'soluciones en supresión de polvo';
include '_header.phtml';
?>

<main role="main">

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">

            <div class="carousel-item active" style="background-image: url('images/vitrine-lavador-rodas-01.jpg')" aria-label="Controlar Sistemas | Lavador de Ruedas y Chasis;">
            </div>

            <div class="carousel-item" style="background-image: url('images/vitrine-locacao-equipamentos-estrada-de-rodagem-01.jpg')" aria-label="Controlar Sistemas | Alquiler de Equipos para Aspersión en Vías;">
            </div>

            <!--<div class="carousel-item" style="background-image: url('images/example-image-slide.jpg');">
            </div>-->

        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Anterior</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Siguiente</span>
        </a>
    </div>


    <div class="container contato pb-4">
        <h1><strong>Soluciones Innovadoras</strong> en Supresión de Polvo y Control de Emisiones.</h1>



        <form id="meuFormulario" action="_mailSender.php" method="POST">

            <h2>HABLE CON UNO DE NUESTROS ESPECIALISTAS.</h2>
            <h3><strong>¡SOLICITE AQUÍ UN PRESUPUESTO!</strong></h3>

            <input type="text" name="nome" placeholder="Nombre Completo *" required>
            <input type="email" name="email" placeholder="Correo Electrónico *" required>
            <input type="text" placeholder="Nombre de la Empresa *" name="empresa" required>
            <input type="tel" placeholder="Teléfono con Código de Área *" name="telefone" required>

            <select id="produto" name="produto">
                <option value="" selected disabled>¿En qué producto está interesado?</option>
                <option value="Aspersión en Cajas de Camiones">Aspersión en Cajas de Camiones</option>
                <option value="Aspersión en Vías de Rodamiento">Aspersión en Vías de Rodamiento</option>
                <option value="Aspersión en Vagones de Mineral">Aspersión en Vagones de Mineral</option>
                <option value="Aspersión en Patios de Mineral">Aspersión en Patios de Mineral</option>
                <option value="Lavador de Ruedas y Chasis">Lavador de Ruedas y Chasis</option>
                <option value="Aspersión en Trituradoras">Aspersión en Trituradoras</option>
                <option value="Alquiler de Equipos">Alquiler de Equipos</option>
            </select>

            <select id="como_conheceucomo_conheceu" name="como_conheceu">
                <option value="" selected disabled>¿Cómo conoció a Controlar?</option>
                <option value="Buscando en Google">Buscando en Google</option>
                <option value="En LinkedIn">En LinkedIn</option>
                <option value="En Instagram">En Instagram</option>
                <option value="En YouTube">En YouTube</option>
                <option value="En Eventos Comerciales">En Eventos Comerciales</option>
                <option value="Recomendación de Terceros">Recomendación de Terceros</option>
            </select>

            <div id="mensagemFeedback"></div>

            <input type="hidden" name="type" value="orcamento" />
            <input type="hidden" id="recaptchaToken" name="recaptchaToken" value="" />


            <div class="d-flex justify-content-between">
                <p>* Todos los campos son obligatorios</p>
                <button type="submit" id="meuBotao">HABLE CON EL CONSULTOR</button>
            </div>
        </form>



    </div><!-- /.contato -->

    <!-- <div class="especialistas2 p-4 text-center">
            <h4>Somos especialistas <strong>em Despoeiramento.</strong></h4>
        </div> -->

    <div class="only-mobile p-4 text-center bg-white">
        <a href="es/contacto/" class="btn btn-whatsapp">
            <img src="images/ico-whatsapp.png" alt=""> HABLE CON UN ESPECIALISTA
        </a>
    </div>


    <div class="container especialistas py-5 mt-5">

        <div class="row ">
            <div class="col-md-6">
                <h2>
                    Especialistas en Supresión de Polvo
                    <strong>y Control de Emisiones de Partículas.</strong>

                    <div class="image-box my-3" aria-label="Equipo especializado en supresión de polvo, desarrollando soluciones para el control de emisiones industriales con un enfoque en la sostenibilidad.;"></div>
                </h2>
            </div>
            <div class="col-md-6 d-flex flex-column justify-content-start">

                <p>La creciente preocupación ambiental y el compromiso con la sostenibilidad en todos los sectores industriales han generado una demanda cada vez mayor por soluciones eficaces para controlar las emisiones de partículas en suspensión resultantes de los procesos productivos.</p>

                <p>CONTROLAR nació con el propósito de atender a empresas que buscan minimizar estas emisiones a lo largo de sus cadenas productivas. Nuestro equipo multidisciplinario, formado por gestores experimentados e ingenieros altamente calificados, desarrolla proyectos innovadores y totalmente automatizados. Nuestro objetivo es ofrecer soluciones personalizadas que garanticen excelencia, eficiencia operativa y valor agregado, satisfaciendo las necesidades específicas de cada cliente.</p>

            </div>
        </div>

    </div><!-- /.especialistas -->

    <div class="equipamentos pt-5">
        <div class="container">

            <h2>
                Nuestros <br>
                <strong>Equipos y Servicios</strong>
            </h2>

            <p class="feature">Ofrecemos mantenimiento preventivo y correctivo para nuestros proyectos.</p>


            <div id="myCarouselEquipamentos" class="carousel slide only-desktop" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#myCarouselEquipamentos" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarouselEquipamentos" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">

                    <!-- INICIO ITEM  -->
                    <div class="carousel-item active">
                        <div class="row">

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-aspersao-em-vagoes-de-minerio.jpg)" aria-label="Supresión de Polvo - Aspersión en Vagones de Mineral | Control de Emisión de Material Particulado a lo Largo de las Vías Férreas.;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">EQUIPO INNOVADOR</div>
                                    <div class="title">ASPERSIÓN EN VAGONES DE MINERAL</div>
                                    <p>Reduzca la pérdida de materiales finos durante el transporte ferroviario y controle la emisión de material particulado a lo largo de la vía férrea.</p>
                                    <div class="btn-box">
                                        <a href="es/aspersion-en-vagones-de-mineral" target="_self" class="text-uppercase btn-more">Más información</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-aspersao-em-vias-ou-pista-de-rolamento-asperroad.jpg)" aria-label="Aspersión en vías o pistas de rodamiento. Controla la emisión de material particulado en vías o pistas de rodamiento industriales | AsperRoad.;">
                                    </div>
                                    <!--<div class="featured"><img src="images/ico-arrow.png" alt="">EQUIPAMENTO
                                        INOVADOR</div>-->
                                    <div class="title">ASPERSIÓN EN VÍAS O PISTAS DE RODAMIENTO</div>
                                    <p>Aspersión (supresión de polvo) en vías o pistas de rodamiento (AsperRoad) mediante el control de la emisión de material particulado.</p>
                                    <div class="btn-box">
                                        <a href="es/aspersion-en-vias-de-rodamiento/" target="_self" class="text-uppercase btn-more">Más información</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-de-grandes-pilhas-de-minerio-aspermovel-para-controle-de-emissoes-fugitivas-de-poeira.jpg)" aria-label="Supresión de polvo en grandes pilas de mineral para el control de emisiones fugitivas de polvo | Aspermóvil;">
                                    </div>
                                    <!--<div class="featured"><img src="images/ico-arrow.png" alt="">Sistema inédito!
                                    </div>-->
                                    <div class="title">SUPRESIÓN DE POLVO EN PILAS DE MINERAL</div>
                                    <p>Supresión de polvo en pilas de mineral para el control de emisiones fugitivas de polvo.</p>
                                    <div class="btn-box">
                                        <a href="es/aspersion-en-patios-de-mineral/" target="_self" class="text-uppercase btn-more">Más información</a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <!-- FIM ITEM -->

                    <!-- INICIO ITEM  -->
                    <div class="carousel-item">
                        <div class="row">

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/eliminar-poeira-lavador-de-rodas.jpg)" aria-label="Lavador de Ruedas - Sistema automático de limpieza que garantiza la eliminación completa de residuos mediante chorro de agua | AsperWash;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">¡SISTEMA INNOVADOR!
                                    </div>
                                    <div class="title">LAVADOR DE RUEDAS Y CHASIS</div>
                                    <p>Sistema automático de limpieza (AsperWash) que garantiza la eliminación completa de residuos mediante chorro de agua.</p>
                                    <div class="btn-box">
                                        <a href="es/lavador-de-ruedas-y-chasis/" target="_self" class="text-uppercase btn-more">Más información</a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/aspersao-em-correias-transportadora-de-britagem.jpg)" aria-label="Aspersión en Cintas Transportadoras de Trituración | AsperBelt;">
                                    </div>

                                    <div class="title">SOLUCIÓN EN ASPERSIÓN PARA TRITURACIÓN</div>
                                    <p>Supresión de polvo y control de partículas (AsperBelt) en cintas transportadoras de trituración, en transportadores y puntos de transferencia.</p>
                                    <div class="btn-box">
                                        <a href="es/aspersion-en-trituradoras/" target="_self" class="text-uppercase btn-more">Más información</a>
                                    </div>
                                </div>
                            </div>

                            <!--<div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>

                                    <div class="title">Quos sequi voluptatem #2 </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" target="_self" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>-->
                        </div>
                    </div>
                    <!-- FIM ITEM -->


                </div>
                <a class="carousel-control-prev" href="#myCarouselEquipamentos" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Anterior</span>
                </a>
                <a class="carousel-control-next" href="#myCarouselEquipamentos" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Siguiente</span>
                </a>
            </div>


            <div id="myCarouselEquipamentosMobile" class="carousel slide only-mobile" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="1"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="2"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="3"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="4"></li>
                    <li data-target="#myCarouselEquipamentosMobile" data-slide-to="5"></li>
                </ol>
                <div class="carousel-inner">

                    <div class="carousel-item active">

                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-aspersao-em-vagoes-de-minerio.jpg)" aria-label="Supresión de Polvo - Aspersión en Vagones de Mineral | Control de Emisión de Material Particulado a lo Largo de las Vías Férreas.;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">EQUIPO INNOVADOR</div>
                                    <div class="title">ASPERSIÓN EN VAGONES DE MINERAL</div>
                                    <p>Reduzca la pérdida de materiales finos durante el transporte ferroviario y controle la emisión de material particulado a lo largo de la vía férrea.</p>
                                    <div class="btn-box">
                                        <a href="es/aspersion-en-vagones-de-mineral/" target="_self" class="text-uppercase btn-more">Más información</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-aspersao-em-vias-ou-pista-de-rolamento-asperroad.jpg)" aria-label="Aspersión en vías o pistas de rodamiento. Controla la emisión de material particulado en vías o pistas de rodamiento industriales | AsperRoad.;">
                                    </div>

                                    <div class="title">ASPERSIÓN EN VÍAS O PISTAS DE RODAMIENTO</div>
                                    <p>Aspersión (supresión de polvo) en vías o pistas de rodamiento (AsperRoad) mediante el control de la emisión de material particulado.</p>
                                    <div class="btn-box">
                                        <a href="es/aspersion-en-vias-de-rodamiento/" target="_self" class="text-uppercase btn-more">Más información</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item ">
                        <div class="row">
                            <div class="col-md-4">

                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/despoeiramento-de-grandes-pilhas-de-minerio-aspermovel-para-controle-de-emissoes-fugitivas-de-poeira.jpg)" aria-label="Supresión de Polvo en Grandes Pilas de Mineral para el Control de Emisiones Fugitivas de Polvo | Aspermóvil;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">¡SISTEMA INNOVADOR!
                                    </div>
                                    <div class="title">SUPRESIÓN DE POLVO EN PILAS DE MINERAL</div>
                                    <p>Sistema automático de limpieza (AsperWash) que garantiza la eliminación completa de residuos mediante chorro de agua.</p>
                                    <div class="btn-box">
                                        <a href="es/aspersion-en-patios-de-mineral/" target="_self" class="text-uppercase btn-more">Más información</a>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/eliminar-poeira-lavador-de-rodas.jpg)" aria-label="Lavador de Ruedas - Sistema automático de limpieza que garantiza la eliminación completa de residuos mediante chorro de agua | AsperWash;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">¡SISTEMA INNOVADOR!</div>
                                    <div class="title">LAVADOR DE RUEDAS Y CHASIS</div>
                                    <p>Sistema automático de limpieza (AsperWash) que garantiza la eliminación completa de residuos mediante chorro de agua.</p>
                                    <div class="btn-box">
                                        <a href="es/lavador-de-ruedas-y-chasis/" target="_self" class="text-uppercase btn-more">Más información</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/aspersao-em-correias-transportadora-de-britagem.jpg)" aria-label="Aspersión en Cintas Transportadoras de Trituración | AsperBelt;">
                                    </div>
                                    <div class="featured"><img src="images/ico-arrow.png" alt="">¡SISTEMA INNOVADOR!
                                    </div>
                                    <div class="title">SOLUCIÓN EN ASPERSIÓN PARA TRITURACIÓN</div>
                                    <p>Supresión de polvo y abatimiento de partículas (AsperBelt) en transportadores de trituración, cintas transportadoras y puntos de transferencia.</p>
                                    <div class="btn-box">
                                        <a href="es/aspersion-en-trituradoras/" target="_self" class="text-uppercase btn-more">Más información</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--<div class="carousel-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="box">
                                    <div class="image-box" style="background-image: url(images/example-image.jpg);">
                                    </div>

                                    <div class="title">Quos sequi voluptatem #2 </div>
                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus
                                        reiciendis tempore
                                        tempora numquam dicta natus et, deleniti esse incidunt iste totam officiis
                                        ab</p>
                                    <div class="btn-box">
                                        <a href="#" target="_self" class="text-uppercase btn-more">Saiba mais</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>-->



                </div>
                <a class="carousel-control-prev" href="#myCarouselEquipamentosMobile" role="button"
                    data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Anterior</span>
                </a>
                <a class="carousel-control-next" href="#myCarouselEquipamentosMobile" role="button"
                    data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Siguiente</span>
                </a>
            </div>



        </div>
    </div><!-- /.equipamentos -->

    <!-- <div class="bg-white p-4 only-mobile">
        <div class="col-md-12">
            <a href="#" class="text-uppercase btn-more">Ver más productos</a>
        </div>
    </div> -->

    <div class="container py-5 text-center clientes">
        <h2>Algunos de <strong>nuestros clientes</strong></h2>

        <div class="w-100 flex justify-content-center align-items-center">
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-vale.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-anglo.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-csn.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-votorantim.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-inb.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-alcoa.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-avante.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-mrs.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-itaminas.png" alt=""></a>
            <a href="#" target="_blank"><img class="zoom" src="images/cliente-groupmoura.png" alt=""></a>
        </div>

    </div><!-- /.clientes -->

</main>

<? include '_footer.phtml'; ?>