<?
$title = 'Lavador de Ruedas y Chasis | Limpieza Eficiente para Vehículos';
$description = 'Descubra el Lavador de Ruedas y Chasis de Controlar. Una solución eficaz para la limpieza de vehículos, garantizando eficiencia, seguridad y sostenibilidad.';
$keywords = 'Lavador de Ruedas y Chasis';
include '_header.phtml';
?>

<main role="main" class="internal">

    <div class="breadcrumb d-flow container">
        <h1><b>SUPRESIÓN DE POLVO</b> - LAVADOR DE RUEDAS Y CHASIS</h1>
    </div>

    <div class="bg-white ">
        <div class="container p-5 solucoes">
            <div class="border-1 mx-5 p-5">
                <h2 class="big">OBJETIVO:</h2>
                <p>Eliminar el polvo y otros residuos inherentes al transporte terrestre.</p>

                <p>El lavador de chasis desarrollado por Controlar es un sistema automático de limpieza que garantiza la eliminación completa de residuos mediante el chorro de agua. Está diseñado para limpiar la parte inferior de los chasis de vehículos, así como los neumáticos.</p>

                <p>El sistema también permite la limpieza de todo tipo de vehículos de carretera y está construido conforme a las normas brasileñas.</p>
                
                <p>Para alcanzar este objetivo, proponemos la instalación de un sistema de lavado que distribuye el agua a través de boquillas de alta presión, asegurando una limpieza uniforme de todas las áreas del vehículo. Esto reduce y elimina los residuos adheridos que podrían ser transportados y depositados en las vías externas.</p>
            </div>
        </div>
    </div>

    <div class="bg-silver">
        <div class="container p-5 solucoes">


            <div class="image text-center mx-5 px-5">
                <img src="images/eliminar-poeira-lavador-de-rodas.jpg" class="img-responsive mx-" alt="Lavador de ruedas y chasis para una limpieza eficiente de vehículos industriales y control de residuos y polvo.">
            </div>

            <div class=" mx-5 p-5">
                <h2 class="big">FUNCIONAMIENTO:</h2>
                <p>El sistema es controlado por sensores y totalmente automatizado, permitiendo la circulación controlada del agua tanto en circuito cerrado como en circuito completo.</p>
                
                <p>Este sistema está diseñado para lavar los neumáticos y la parte inferior de los chasis de camiones y maquinaria. El lavador de ruedas y chasis ya está operativo en minas, plantas industriales y puertos, eliminando eficazmente todo el material impregnado en estos transportes.</p>
                
                <p>Todo el proceso de lavado es automático, gestionado por sensores que controlan la entrada y salida de los vehículos. A medida que los chorros de agua son lanzados por las boquillas, la suciedad es arrastrada a través de una rejilla, eliminando completamente los residuos adheridos a los neumáticos y chasis.</p>
                
                <p>Los residuos eliminados se depositan en el fondo del lavador y son transportados directamente a tanques de decantación (de concreto) con separadores de aceite o dirigidos a un área de desecho.</p>
            </div>
        </div>
    </div>


    <div class=" solucoes bg-green container">
        <div class="pt-5 px-5 pb-0 solucoes ">
            <div class=" mx-5 pt-5 px-5 pb-0 ">
                <h2 class="big">VENTAJAS:</h2>

                <ul class="list">
                    <li>Control de impactos ambientales;</li>
                    <li>Bajo costo de operación;</li>
                    <li>Bajo costo de mantenimiento;</li>
                    <li>Evita el desperdicio de agua;</li>
                    <li>Eliminación completa de residuos.</li>
                </ul>

                <br>

                <h2 class="big">APLICACIONES:</h2>

                <ul class="list">
                    <li>Salidas de plantas industriales diversas (minería, cementeras, siderúrgicas, etc.);</li>
                    <li>Áreas internas de plantas industriales;</li>
                    <li>Puertos.</li>
                </ul>

                <br>
                <br>

            </div>

            <!--<div class="youtube-container solucoes">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>-->
        </div>
    </div>




    <div class="bg-white ">
        <div class="d-mobile-none" style="height: 150px;"></div>

        <div class="p-5 text-center">
            <a href="/es/contacto/" target="_self" class="btn btn-more fs-2">SOLICITE UN CONTACTO</a>
        </div>

    </div>

</main>

<? include '_footer.phtml'; ?>