<?
$title = 'Soluciones en Supresión de Polvo, Aspersión en Vagones de Mineral, Vías y Pistas de Rodamiento, Control y Reducción de Polvo';
$description = '';
$keywords = '';
include '_header.phtml';
?>

<main role="main" class="internal">


    <div class="breadcrumb container">
        <h1><b>Nuestros clientes y socios</b></h1>
    </div>

    <div class="bg-white ">

        <div class="container py-5 text-center clientes">


            <div class="w-100 flex justify-content-center align-items-center">
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-vale.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-anglo.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-csn.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-votorantim.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-inb.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-alcoa.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-avante.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-mrs.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-itaminas.png" alt=""></a>
                <a href="#" target="_blank"><img class="zoom" src="images/cliente-groupmoura.png" alt=""></a>
            </div>

        </div>



    </div><!-- /.clientes -->



    <div class="p-5 text-center">
        <a href="/es/contacto/" target="_self" class="btn btn-more fs-2">SOLICITE UN CONTACTO</a>
    </div>

</main>


<? include '_footer.phtml'; ?>