<?
$title = 'Proyectos Innovadores de Supresión de Polvo | Soluciones Personalizadas Controlar';
$description = 'Explore proyectos innovadores de supresión de polvo desarrollados por Controlar. Descubra soluciones personalizadas y eficientes para el control de polvo industrial.';
$keywords = 'proyectos innovadores de supresión de polvo';
include '_header.phtml';
?>


<main role="main" class="internal">


    <div class="breadcrumb container">
        <h1><b>PROYECTOS INNOVADORES</b></h1>
    </div>

    <div class="bg-white">

        <div class="container projetos">

            <h3 class="text-center py-5">Conozca algunos de nuestros proyectos innovadores</h3>


            <!-- Item -->
            <div class="bg-silver"></div>
            <div class="z-100">

                <div class="px-5">
                    <h2 class="pt-4 pb-3 px-5">Aspermóvil | Solución Móvil para el Control de Polvo</h2>
                    <p class="px-5">Descubra Aspermóvil, una solución móvil e innovadora para la aspersión y el control de polvo. Ideal para patios, vías de rodamiento y entornos que requieren flexibilidad operativa.</p>
                </div>

                <div class="youtube-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/2tMY9oX7T1Q?si=IOgRkqdtZr4UUd9_"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>


            <!-- Item -->
            <div class="bg-silver"></div>
            <div class="z-100">

                <div class="px-5">
                    <h2 class="pt-4 pb-3 px-5">AsperWagon | Aspersión en Vagones de Mineral</h2>
                    <p class="px-5">Vea AsperWagon en acción, garantizando un control eficiente del polvo en vagones de mineral, con tecnologías avanzadas y resultados sostenibles.</p>
                </div>


                <div class="youtube-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/Bwacn0D1x2M?feature=oembed"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>


            <!-- Item -->
            <div class="bg-silver"></div>
            <div class="z-100">

                <div class="px-5">
                    <h2 class="pt-4 pb-3 px-5">AsperWash | Sistema Innovador de Lavado de Ruedas y Chasis</h2>
                    <p class="px-5">Descubra AsperWash, una solución eficiente para el lavado de ruedas y chasis en entornos industriales. Reduzca residuos y garantice la limpieza con sostenibilidad y alto rendimiento.</p>
                </div>


                <div class="youtube-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/oAHTm_oDckg?si=kJCNeRidAIP4fvbO"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>

        </div>


        <div class="pb-5 text-center">
            <a href="/es/contacto/" target="_self" class="btn btn-more fs-2 w-400">¿DUDAS? SOLICITE UN CONTACTO</a>
        </div>

    </div>

</main>


<? include '_footer.phtml'; ?>