<?
$title = 'Especialistas en Supresión de Polvo | Sobre Controlar';
$description = 'Conozca a Controlar, especialistas en supresión de polvo y soluciones innovadoras para el control de emisiones. Descubra nuestra historia y compromiso con la sostenibilidad.';
$keywords = 'especialistas en supresión de polvo';
include '_header.phtml';
?>

<main role="main" class="internal">


    <div class="breadcrumb container">
        <h1><b>Quiénes somos</b></h1>
    </div>

    <div class="bg-white quem-somos">

        <div class="container py-5">

            <div class="row">
                <div class="col-md-6">
                    <h2><strong>Somos especialistas</strong> <br>
                        en Supresión de Polvo.</h2>

                    <img src="images/example-image.jpg" class="img-responsive mt-1" alt="Equipo de especialistas en supresión de polvo de Controlar, dedicado al control de polvo industrial.">
                </div>
                <div class="col-md-6 d-flex flex-column justify-content-end">
                    <p>El aumento de la preocupación ambiental y el enfoque en la sostenibilidad en todos los sectores de la industria mundial implican diversas necesidades. Una de las principales es la necesidad de controlar las emisiones de materiales particulados suspendidos generados por los procesos productivos.</p>

                    <p>CONTROLAR surgió para atender a las empresas que desean controlar estas emisiones en las diversas situaciones de la cadena productiva. En CONTROLAR, un equipo multidisciplinario y altamente calificado, compuesto por gestores e ingenieros de alto nivel técnico, es responsable de desarrollar proyectos innovadores y completamente automatizados para garantizar la excelencia, el valor agregado de los proyectos elaborados y satisfacer las necesidades específicas de cada cliente.</p>
                </div>
            </div>


        </div><!-- /.quem somos -->


    </div>

    <div class="bg-green quem-somos py-5">

        <div class="container">

            <h3>NUESTRA MISIÓN</h3>
            <p>Desarrollar proyectos innovadores de sistemas de supresión de polvo mediante alta tecnología para promover el bienestar y la sostenibilidad.</p>

            <h3>NUESTRA VISIÓN</h3>
            <p>Alcanzar la admiración y el respeto de los clientes a través de la aplicabilidad, la confiabilidad y la practicidad de los proyectos desarrollados.</p>

            <h3>NUESTROS VALORES</h3>

            <ul>
                <li><strong>INNOVACIÓN:</strong> Ofrecer al mercado productos excepcionales, desarrollados con alta tecnología, para satisfacer las necesidades individuales de cada cliente.</li>
                <li><strong>SOSTENIBILIDAD:</strong> Presentar soluciones con bajos costos operativos que promuevan principalmente el ahorro de energía y la reutilización del agua.</li>
                <li><strong>COMPROMISO:</strong> Entregar todos los proyectos cumpliendo con las normas vigentes y los plazos establecidos.</li>
                <li><strong>ÉTICA:</strong> Respetar a los colaboradores, clientes y proveedores para consolidar relaciones sólidas y transparentes.</li>
            </ul>


        </div>

    </div>


    <div class="p-5 text-center">
        <a href="/es/contacto/" target="_self" class="btn btn-more fs-2">SOLICITE UN CONTACTO</a>
    </div>

</main>


<? include '_footer.phtml'; ?>